Giveth/giveth-dapps-v2

- src/components/cards/Connect.tsx
This will reflect changes happened by https://github.com/Giveth/liquidity-mining-dapp/pull/145
> Refs giveth/giveconomy#463

- public/images/arrow_left_searchbox.svg
- src/apollo/apolloClient.ts
- src/components/SearchBox.tsx
- src/components/badges/CategoryBadge.tsx
- src/components/views/FAQIndex.tsx
- src/components/views/project/ProjectDonationTable.tsx
- src/components/views/projects/ProjectsIndex.tsx
- src/components/views/projects/ProjectsNoResults.tsx
- styles/globals.css
Related to issue [#46](https://github.com/Giveth/giveth-io-typescript/issues/46) in typescript repo
> H 46 search box problems

- src/components/SearchBox.tsx
- src/components/badges/ShareLikeBadge.tsx
- src/components/badges/VerificationBadge.tsx
- src/components/views/project/ProjectDonateCard.tsx
- src/components/views/project/ProjectDonationTable.tsx
- src/components/views/project/ProjectHeader.tsx
- src/components/views/project/ProjectIndex.tsx
- src/components/views/project/ProjectTotalFundCard.tsx
- src/components/views/projects/ProjectsIndex.tsx
- styles/globals.css
> Fix projects page style

- src/components/homeTabs/GIVstream.tsx
- src/components/modals/GIVdropHarvestModal.tsx
Applied fixes of https://github.com/Giveth/liquidity-mining-dapp/pull/155
> giveconomy patch

- src/components/Footer/Footer.tsx
- src/components/RichTextViewer.tsx
- src/components/views/project/ProjectDonateCard.tsx
- src/components/views/project/ProjectHeader.tsx
- src/components/views/project/ProjectIndex.tsx
- src/components/views/project/ProjectTabs.tsx
> Style of project single page

- src/context/price.context.tsx
Replace crypto-compare price endpoint with trace backend (feathers)
Refs giveth/giveconomy#478
> Change eth price endpoint

- src/components/Footer/Footer.tsx
- src/components/RichTextViewer.tsx
- src/components/views/project/ProjectDonateCard.tsx
- src/components/views/project/ProjectHeader.tsx
- src/components/views/project/ProjectIndex.tsx
- src/components/views/project/ProjectTabs.tsx
Reverts Giveth/giveth-dapps-v2#27
> Revert "Style of project single page"

- src/components/Header/Header.tsx
- src/components/Tabs.tsx
- src/lib/helpers.ts
> Fix GIVeconomy header

- src/components/Footer/Footer.tsx
- src/components/RichTextViewer.tsx
- src/components/views/project/ProjectDonateCard.tsx
- src/components/views/project/ProjectHeader.tsx
- src/components/views/project/ProjectIndex.tsx
- src/components/views/project/ProjectTabs.tsx
Reverts Giveth/giveth-dapps-v2#30
> Revert "Revert "Style of project single page""

- src/components/SearchBox.tsx
- src/components/views/projects/ProjectsIndex.tsx
- src/components/views/projects/ProjectsNoResults.tsx
- styles/globals.css
fix search projects: 1. search box pressed color 2. make no results center 3. fix no results z-index
related to [this](https://github.com/Giveth/giveth-io-typescript/issues/46)
> Search projects problems

- package.json
- pages/test.tsx
- src/components/toasts/index.tsx
- src/components/toasts/success.tsx
- src/components/views/projects/ProjectsIndex.tsx
- yarn.lock
> Add Toasts

- src/apollo/gql/gqlProjects.ts
- src/components/project-card/ProjectCard.tsx
- src/components/project-card/ProjectCardAlt.tsx
- src/components/views/project/ProjectHeader.tsx
Ref Giveth/giveth-io-typescript#42﻿
> Feat to redirect to authors page

- src/apollo/types/gqlEnums.ts
- src/components/views/projects/ProjectsIndex.tsx
Ref Giveth/giveth-io-typescript#48﻿
> Fix sort by labels

- package.json
- src/apollo/gql/gqlUser.ts
- src/apollo/types/types.ts
- src/components/views/userPublicProfile/PublicProfileDonationsTab.tsx
- src/helpers/blockchain.ts
- yarn.lock
- giveth/giveth-io-typescript#41
> Add hover and link to donation table

- src/components/views/about/AboutHistory.tsx
- src/components/views/about/AboutIndex.tsx
- src/components/views/about/AboutTeam.tsx
- src/content/GivethTeam.json
Ref Giveth/giveth-io-typescript#50
> Fix about page

- src/components/Footer/Footer.tsx
- yarn.lock
Ref Giveth/giveth-io-typescript#86﻿
> Fix docs footer icon

- src/apollo/gql/gqlProjects.ts
- src/components/Footer/Footer.tsx
- src/components/RichTextInput.tsx
- src/components/menu/MenuWallet.tsx
- src/components/modals/Modal.tsx
- src/components/modals/WelcomeSigninModal.tsx
- src/components/styled-components/Arc.ts
- src/components/views/homepage/HomePurpleSection.tsx
- src/components/views/project/ProjectDonateCard.tsx
- src/components/views/project/ProjectDonations.tsx
- src/components/views/project/ProjectIndex.tsx
- src/components/views/project/ProjectTimeline.tsx
- src/components/views/project/ProjectUpdates.tsx
- src/components/views/userPublicProfile/PublicProfileContributeCard.tsx
- src/components/views/userPublicProfile/PublicProfileContributes.tsx
- src/components/views/userPublicProfile/PublicProfileLikedTab.tsx
- src/components/views/userPublicProfile/PublicProfileOverviewTab.tsx
- src/components/views/userPublicProfile/PublicProfileProjectsTab.tsx
- src/components/views/userPublicProfile/UserPublicProfile.view.tsx
- styles/globals.css
Reverts Giveth/giveth-dapps-v2#108
> Revert "Feature/project updates"

- package.json
- src/components/project-card/ProjectCardBadges.tsx
- yarn.lock
> Like and share new design

- src/components/homeTabs/GIVbacks.tsx
- src/components/modals/GIVBackExplain.tsx
- src/components/views/project/ProjectDonateCard.tsx
- src/lib/constants/links.ts
> implement givback toast new design

- next.config.js
- src/components/AmountInput.tsx
- src/components/cards/Donate.tsx
- src/components/cards/Govern.tsx
- src/components/cards/Stake.tsx
https://github.com/Giveth/giveth-dapps-v2/issues/112
> Giveth pinata gateway is allowed as image source

- next.config.js
- src/components/AmountInput.tsx
- src/components/ImageUploader.tsx
- src/components/Input.tsx
- src/components/cards/Donate.tsx
- src/components/cards/Govern.tsx
- src/components/cards/Stake.tsx
- src/components/modals/EditUserModal.tsx
- src/components/views/onboarding/InfoStep.tsx
- giveth/giveth-io-typescript#62
> Edit user validation

- package.json
- src/apollo/gql/gqlProjects.ts
- src/apollo/types/types.ts
- src/components/project-card/ProjectCard.tsx
- src/components/project-card/ProjectCardAlt.tsx
- src/components/project-card/ProjectCardBadges.tsx
- src/components/project-card/ProjectCardImage.tsx
- src/components/views/project/ProjectDonateCard.tsx
- src/lib/helpers.ts
- yarn.lock
> Edit project card

- package.json
- src/apollo/gql/gqlProjects.ts
- src/apollo/types/types.ts
- src/components/views/project/ProjectDonations.tsx
- src/components/views/project/ProjectIndex.tsx
- src/components/views/project/ProjectTotalFundCard.tsx
- yarn.lock
> H 86 fix total trace donations

- src/components/modals/HarvestAll.sc.tsx
- src/components/modals/Modal.tsx
- src/components/modals/ModalHeader.tsx
- src/components/modals/VerificationModal.tsx
- src/components/modals/WelcomeSigninModal.tsx
- src/components/views/project/ProjectDonateCard.tsx
- src/components/views/project/ProjectUpdates.tsx
- src/lib/constants/links.ts
> F 130 verification modal

- src/components/modals/GoodProjectDescription.tsx
Issue #129 
1. remove redundant text
2. improve responsiveness
3. add scrollbar for short screens
> H 129 great project description modal

- src/lib/wallet/walletTypes.ts
> Don't put any restriction for metamask connected wallets.

- src/apollo/gql/gqlProjects.ts
- src/components/project-card/ProjectCardBadges.tsx
- src/components/views/project/ProjectDonateCard.tsx
- src/context/UserProvider.tsx
Added support for unlike projects on `liked projects` tab of account …page, refs #125
Fixed likedProjectsCount update issue
Improved user provider component
> Unlike projects in account page + improvements

- pages/_app.tsx
- src/components/Checkbox.tsx
- src/components/Footer/Footer.tsx
- src/components/RichTextInput.tsx
- src/components/map.tsx
- src/components/modals/ProjectGuidelineModal.tsx
- src/components/modals/SignInModal.tsx
- src/components/views/create/CategoryInput.tsx
- src/components/views/create/Create.sc.tsx
- src/components/views/create/CreateProject.tsx
- src/components/views/create/DescriptionInput.tsx
- src/components/views/create/ImageInput.tsx
- src/components/views/create/LocationInput.tsx
- src/components/views/create/WalletAddressInput.tsx
- src/components/views/homepage/HomeExploreProjects.tsx
- src/components/views/project/ProjectDonateCard.tsx
- src/components/views/project/ProjectHeader.tsx
- src/components/views/project/ProjectIndex.tsx
- src/components/views/project/ProjectTabs.tsx
- src/components/views/project/ProjectTimeline.tsx
- src/components/views/project/ProjectUpdates.tsx
- src/components/views/projects/ProjectsIndex.tsx
- src/components/views/userPublicProfile/PublicProfileLikedTab.tsx
- src/components/views/userPublicProfile/PublicProfileProjectsTab.tsx
- src/configuration.ts
- src/lib/constants/links.ts
- src/lib/helpers.ts
- src/utils/constants.ts
> F 105 create edit a project responsiveness

- src/apollo/gql/gqlDonations.ts
- src/components/views/project/ProjectDonationTable.tsx
- src/components/views/project/ProjectDonations.tsx
- src/components/views/project/ProjectIndex.tsx
> Fix search bar on donation table

- src/components/Footer/Footer.tsx
- src/components/Header/Header.sc.tsx
- src/components/Header/Header.tsx
- src/components/SearchBox.tsx
- src/components/views/FAQIndex.tsx
- src/components/views/create/CreateProject.tsx
- src/components/views/project/ProjectDonationTable.tsx
- src/components/views/projects/ProjectsIndex.tsx
> F 94 projects list responsiveness

- src/context/UserProvider.tsx
https://github.com/Giveth/giveth-dapps-v2/pull/145
> Pushed missed updates of #145

- src/components/modals/DeactivateProjectModal.tsx
- src/components/modals/DonateModal.tsx
- src/components/project-card/ProjectCardBadges.tsx
- src/components/views/project/ProjectDonateCard.tsx
- src/context/UserProvider.tsx
- src/lib/helpers.ts
Fixed not showing sign out when the user has signed in
Fixed issue of setting user when the cookie is empty
Show sign in modal instead of directly signing in.
> Fix/improve authentication token management + sign in

- src/components/Header/Header.tsx
- src/components/views/create/CreateIndex.tsx
- src/context/UserProvider.tsx
check wallet on clicking create project button on header
> check wallet on create project button

- src/components/views/homepage/HomeExploreProjects.tsx
- src/components/views/homepage/HomeHeader.tsx
- src/components/views/projects/ProjectsIndex.tsx
Refs https://github.com/Giveth/GIVeconomy/issues/513
> Added and updated some SEO content

- src/components/modals/EditUserModal.tsx
- src/components/modals/GIVdropHarvestModal.tsx
- src/components/modals/GoodProjectDescription.tsx
- src/components/modals/HarvestAll.sc.tsx
- src/components/modals/HarvestAll.tsx
- src/components/modals/Modal.tsx
- src/components/modals/V3Stake.tsx
- src/components/modals/VerificationModal.tsx
> Make edit profile responsive

- pages/index.tsx
- src/components/project-card/ProjectCard.tsx
- src/components/styled-components/Input.ts
- src/components/views/homepage/Home.sc.ts
- src/components/views/homepage/HomeBlogPost.tsx
- src/components/views/homepage/HomeChangeMakers.tsx
- src/components/views/homepage/HomeExploreProjects.tsx
- src/components/views/homepage/HomeFromBlog.tsx
- src/components/views/homepage/HomeGetUpdates.tsx
- src/components/views/homepage/HomeHeader.tsx
- src/components/views/homepage/HomePurpleSection.tsx
- src/lib/constants/Routes.ts
- styles/globals.css
> F 93 Home Page Responsiveness

- src/apollo/gql/gqlProjects.ts
- src/components/project-card/ProjectCard.tsx
- src/components/project-card/ProjectCardOrgBadge.tsx
> Giving block badge

- src/components/homeTabs/GIVbacks.tsx
- src/components/homeTabs/GIVstream.tsx
- src/components/homeTabs/Overview.tsx
Refs 
- https://github.com/Giveth/giveth-dapps-v2/issues/194
- https://github.com/Giveth/giveth-dapps-v2/issues/196
> Changed projects links

- src/components/views/project/ProjectDonateCard.tsx
Refs https://github.com/Giveth/giveth-dapps-v2/issues/232
> Fixed issue in updating state of ProjectDonateCard.tsx component

- src/components/GeneralCard.tsx
- src/components/project-card/ProjectCard.tsx
- src/components/views/about/AboutIndex.tsx
- src/components/views/homepage/HomePurpleSection.tsx
- src/components/views/join/JoinEngage.tsx
- src/components/views/userPublicProfile/PublicProfileContributeCard.tsx
- src/components/views/userPublicProfile/PublicProfileContributes.tsx
- src/components/views/userPublicProfile/PublicProfileOverviewTab.tsx
> Fix minor UI issues

- pages/donate/[slug].tsx
- src/components/views/project/ProjectIndex.tsx
On donate page it redirects to homepage
On projects view it hides all buttons and shows only the error toast
> F230 cancelled projects handler

- src/components/Footer/Footer.tsx
Refs https://github.com/Giveth/giveth-dapps-v2/issues/196
> Removed DAC line from footer

- src/components/DataBox.tsx
- src/components/Footer/Footer.tsx
- src/components/GIVfrens.sc.tsx
- src/components/GIVfrens.tsx
- src/components/RegenRewardCard.tsx
- src/components/RegenStream.tsx
- src/components/RegenStreamBlock.tsx
- src/components/RewardCard.tsx
- src/components/Tabs.tsx
- src/components/cards/BaseStakingCard.sc.tsx
- src/components/homeTabs/GIVbacks.sc.tsx
- src/components/homeTabs/GIVbacks.tsx
- src/components/homeTabs/GIVfarm.sc.tsx
- src/components/homeTabs/GIVfarm.tsx
- src/components/homeTabs/GIVgarden.sc.tsx
- src/components/homeTabs/GIVgarden.tsx
- src/components/homeTabs/GIVstream.sc.tsx
- src/components/homeTabs/GIVstream.tsx
- src/components/homeTabs/Overview.sc.tsx
- src/components/homeTabs/Overview.tsx
- src/components/homeTabs/commons.tsx
- src/components/styled-components/Flex.tsx
> Giveconomy responsive

- src/components/views/project/ProjectDonationTable.tsx
> Fix Donations list on project

- src/components/NetworkSelector.tsx
- src/components/views/donate/CryptoDonation.tsx
> Fix change network modal

- src/components/views/donate/CryptoDonation.tsx
> Fix token list

- src/components/menu/RewardMenu.tsx
> fix capitalization

- src/components/views/donate/CryptoDonation.tsx
> Fix token value on donate modal

- src/components/views/project/ProjectDonateCard.tsx
> Fix verified project button bug

- src/components/modals/DeactivateProjectModal.tsx
> H 263 fix deactivated Project confirmation Links

- src/components/views/project/ProjectDonateCard.tsx
> H 263 allow edit for draft projects

- src/components/homeTabs/GIVstream.tsx
> Updated garden distributor lists

- src/components/homeTabs/GIVstream.tsx
- src/components/views/project/ProjectDonationTable.tsx
> Fix donation search

- src/components/Checkbox.tsx
- src/components/project-card/ProjectCardBadges.tsx
- src/components/views/donate/CryptoDonation.tsx
- src/components/views/donate/DonateIndex.tsx
> H 284 fix Donation Page weird project card view

- src/components/views/homepage/HomeChangeMakers.tsx
> Fix homepage style

- src/components/views/donate/FiatDonation.tsx
> H 312 add coming soon for transak

- pages/_document.tsx
- pages/claim.tsx
- pages/donate/[slug].tsx
- pages/givbacks.tsx
- pages/giveconomy.tsx
- pages/givfarm.tsx
- pages/givgarden.tsx
- pages/givstream.tsx
- pages/project/[projectIdSlug]/index.tsx
- src/components/views/Back.view.tsx
- src/components/views/project/ProjectIndex.tsx
- src/lib/meta.tsx
> H 305 fix meta for twitter

- src/components/modals/DeactivateProjectModal.tsx
> Fix deactivate project modal issues

- src/apollo/gql/gqlProjects.ts
- src/apollo/types/types.ts
- src/components/views/create/CreateProject.tsx
> Editing project changes

- src/components/views/project/ProjectDonationTable.tsx
> Added network chain to donation table

- pages/api/time.js
- src/helpers/time.ts
Using vercel server time instead of timezonedb service.
> time server change

- src/components/cards/StakingCardIntro.tsx
- Giveth/liquidity-mining-dapp#201
> open link in new tab

- src/components/GIVfrens.sc.tsx
- src/components/GIVfrens.tsx
- src/lib/constants/links.ts
- Giveth/liquidity-mining-dapp#199
> Add dao card

- src/components/project-card/ProjectCard.tsx
> Fix redirect to undefined user page

- src/components/modals/APR.tsx
- src/components/modals/HarvestAll.tsx
- Giveth/liquidity-mining-dapp#196
> Fix harvest apr modals regen farms

- src/components/modals/Modal.tsx
- src/components/modals/WalletModal.tsx
Ref. #294 
1. close modals on escape press
2. close modal on click outside
3. remove unnecessary horizontal scrollbar
> F 294 Make modals more user friendly

- src/components/homeTabs/Overview.tsx
Fixed the projects link in giveconomy overview pages
Refs https://github.com/Giveth/giveth-dapps-v2/issues/194
> Fix a link

- src/components/GIVfrens.tsx
- Giveth/liquidity-mining-dapp#199
> update dao card

- src/components/views/project/ProjectDonateCard.tsx
> Fix logic to display buttons

- src/components/project-card/ProjectCard.tsx
- src/components/project-card/ProjectCardOrgBadge.tsx
> Fix buttons on project card

- src/components/ExternalLink.tsx
- src/components/InternalLink.tsx
- src/components/views/project/ProjectDonateCard.tsx
Ref. #319
1. Show givback for verified projects and hide for admins
2. show "View similar projects" and "Report an issue" for non-admin
> H 319 Show givback notif condition

- src/components/modals/ChangeNetwork.tsx
> Fix suggested networks on modal

- src/components/Header/Header.tsx
- src/components/menu/RewardMenu.tsx
> Fix modal closing when cursor leaves DOM

- src/utils/Logger.ts
Read sentry setting from environmental variables
> Sentry config

- src/components/modals/APR.tsx
- src/components/modals/HarvestAll.tsx
> Fix grammar issues on RegenStream

- package.json
- src/components/GIVfrens.tsx
* Fixed regen farm learn more link
> Release 2.2.1

- src/components/views/donate/DonateIndex.tsx
> Fix project name on congratulations page

- src/components/AddTokenButton.tsx
- src/components/cards/Claim.tsx
- src/components/cards/Congratulations.tsx
- src/components/modals/ConfirmSubmit.tsx
- src/components/modals/HarvestAll.tsx
- src/lib/metamask/index.ts
Changed AddGIVToken component to a more generalized AddToken which support others token too and not only GIV
Refs https://github.com/Giveth/giveth-dapps-v2/issues/419
> Supported RegenFarm add token

- src/components/views/homepage/HomeChangeMakers.tsx
- src/components/views/homepage/HomePurpleSection.tsx
> Fix homepage allignment

- src/components/GIVfrens.sc.tsx
- src/components/homeTabs/GIVbacks.sc.tsx
- src/components/homeTabs/GIVgarden.sc.tsx
- src/components/homeTabs/GIVgarden.tsx
- src/components/homeTabs/Overview.sc.tsx
fixes to mobile responsiveness
> Mobile resp giveconomy

- src/components/GIVfrens.tsx
> Fix regen farm learn more link

- src/components/modals/DonateModal.tsx
> Fix button hover animation

- src/components/AmountInput.tsx
> change active percentage color on stake modal

- src/components/AmountInput.tsx
Max button makes the 100% button high light
> Max Button and Percentage Button integration

- src/components/views/create/CreateProject.tsx
> F 456 show cancel button for edit mode only

- src/components/project-card/ProjectCardOrgBadge.tsx
> fix 505 badge of projects overlay on drop-down menus

- src/components/modals/DeactivateProjectModal.tsx
- src/components/modals/ShareModal.tsx
- src/components/project-card/ProjectCard.tsx
- src/components/project-card/ProjectCardAlt.tsx
- src/components/project-card/ProjectCardBadges.tsx
- src/components/views/donate/ProjectCardSelector.tsx
- src/components/views/donate/SuccessView.tsx
- src/components/views/project/ProjectDonateCard.tsx
- src/lib/routeCreators.tsx
> fix link to project on donate page + fix share modal copy link

- package.json
- src/components/modals/Modal.tsx
- src/components/modals/ModalHeader.tsx
- src/components/modals/WelcomeModal.tsx
- yarn.lock
Removed React-Modal package and fixed new modal issue
> Removed React-Modal package and fixed new modal issue

- src/components/modals/APR.tsx
- src/lib/contractHelper/TokenDistroHelper.ts
Improved globallyClaimableNow calculation
Refs #513
> Fixed GlobalReleasePercentage calculation issue

- src/config/development.ts
- src/config/production.ts
- src/lib/wallet/walletTypes.ts
- src/types/config.ts
Set rpc urls of walletconnect for mainnet and xdai networks
Removed unused rpcUrls fields
> Wallet connect + gnosis-safe

- src/components/views/project/NotAvailableProject.tsx
- src/components/views/project/ProjectDonateCard.tsx
- src/components/views/project/ProjectIndex.tsx
- src/components/views/project/ProjectUpdates.tsx
> donate card should be under drop-down menu

- src/lib/subgraph/subgraphDataTransform.ts
- src/lib/subgraph/subgraphQueryBuilder.ts
- src/types/subgraph.ts
Removed unused rewardsUniswap and rewardPerTokenPaidUniswap from subgraph queries
> Removed unused variables from subgraph query

- src/components/views/userPublicProfile/UserPublicProfile.view.tsx
> F 547 fix torus images

- src/components/Header/Header.sc.tsx
- src/components/cards/BaseStakingCard.sc.tsx
- src/components/modals/Modal.tsx
- src/lib/constants/constants.ts
> Fixed GivFarm zIndex issue and created constant for some zIndexes

- src/context/positions.context.tsx
- src/hooks/useStakingNFT.tsx
- src/lib/contracts.ts
- src/lib/subgraph/subgraphDataTransform.ts
Fixed issue in loading uniswapv3 config
> Load uniswapV2 unipool data from subgraph

- src/components/modals/FirstWelcomeModal.tsx
- src/components/modals/WalletModal.tsx
Modal was being shown even when rejecting the login
> Welcome modal shown only when user actually logs in

- src/components/cards/BaseStakingCard.tsx
- src/config/development.ts
- src/config/production.ts
- src/types/config.ts
> Set startTime for giv/dai farm

- src/components/views/userPublicProfile/IncompleteProfileToast.tsx
- src/components/views/userPublicProfile/PublicProfileContributeCard.tsx
- src/components/views/userPublicProfile/PublicProfileContributes.tsx
- src/components/views/userPublicProfile/PublicProfileLikedTab.tsx
- src/components/views/userPublicProfile/PublicProfileOverviewTab.tsx
- src/components/views/userPublicProfile/UserPublicProfile.view.tsx
- src/components/views/userPublicProfile/projectsTab/PublicProfileProjectsTab.tsx
- src/helpers/number.ts
> 554 fix some issues on my account

- src/lib/wallet.ts
> show test error if the Metmask is not available on switch network

- pages/project/[projectIdSlug]/index.tsx
- src/components/views/project/ProjectDonateCard.tsx
- src/config/development.ts
> Fix project hydration page

- pages/project/[projectIdSlug]/index.tsx
- src/components/views/project/ProjectDonateCard.tsx
Reverts Giveth/giveth-dapps-v2#586
> Revert "Fix project hydration page"

- src/lib/contractHelper/UnipoolHelper.ts
- src/lib/subgraph/subgraphDataTransform.ts
- src/types/subgraph.ts
UnipoolHelper returns zero reward amount after the periodFinish timestamp
Refs #397
> Support periodFinish in UnipoolHelper reward

- src/components/modals/Modal.tsx
> make scrollbar dynamic

- src/components/views/userPublicProfile/PublicProfileContributeCard.tsx
- src/components/views/userPublicProfile/PublicProfileContributes.tsx
- src/lib/helpers.ts
> fix NaN for donations in my account

- src/components/homeTabs/GIVstream.tsx
- yarn.lock
> Add givdai to stream history

- src/components/homeTabs/GIVfarm.tsx
- src/components/homeTabs/Overview.sc.tsx
- src/components/homeTabs/Overview.tsx
- src/components/homeTabs/commons.tsx
> Add buy giv token

- src/components/GeneralCard.sc.tsx
- src/components/views/join/JoinSubscriptionCard.tsx
Added min width for join subscription button and made cards smaller
> Fixed join page card styles

- src/context/ModalProvider.tsx
- src/context/UserProvider.tsx
- src/context/claim.context.tsx
- src/context/farm.context.tsx
- src/context/general.context.tsx
- src/context/positions.context.tsx
- src/context/price.context.tsx
- src/context/subgraph.context.tsx
- src/context/theme.context.tsx
- src/context/tokenDistro.context.tsx
#658 
Added displayName for our React contexts.
> Added displayName for our contexts

- src/components/views/donate/SocialBox.tsx
> Fixed create project title and url

- src/components/views/partnerships/PartnershipsIndex.tsx
> Sorted Partners Alphabetically

- src/components/views/Errors/ErrorsIndex.sc.ts
- src/components/views/Errors/ErrorsIndex.tsx
- src/components/views/Errors/MaintenanceIndex.tsx
> Linked Giveth logo to Hamepage in error and maintenance pages

- .eslintrc
- src/components/RichTextInput.tsx
- src/lib/helpers.ts
> Added new eslint rule for named-imports

- src/components/views/homepage/HomeFromBlog.tsx
- src/components/views/project/ProjectDonateCard.tsx
> Fix from our blog not showing

- src/apollo/gql/gqlDonations.ts
- src/apollo/gql/gqlUser.ts
- src/apollo/types/gqlEnums.ts
- src/apollo/types/types.ts
- src/components/views/donate/DonateIndex.tsx
- src/components/views/donate/DonationTypes.tsx
- src/components/views/donate/helpers.tsx
- src/components/views/project/ProjectDonationTable.tsx
- src/components/views/project/ProjectDonations.tsx
- src/components/views/userPublicProfile/donationsTab/DonationsTable.tsx
- src/lib/helpers.ts
- src/services/donation.ts
> new service for donation save and donation update

- src/components/cards/Govern.tsx
- src/components/cards/Stake.tsx
- src/hooks/useStakingPool.tsx
- src/lib/contractHelper/UnipoolHelper.ts
- src/lib/stakingPool.ts
> Used unipoolHelper in calculating APR

- src/components/views/donate/TokenPicker.tsx
> remove captureException from token picker icon catch function

- src/components/views/donate/SocialBox.tsx
> Removed Emojis from share on fb

- pages/_app.tsx
- src/components/RegenStreamCard.tsx
- src/components/RewardCard.tsx
- src/components/cards/BaseStakingCard.tsx
- src/components/cards/Congratulations.tsx
- src/components/cards/Donate.tsx
- src/components/cards/Govern.tsx
- src/components/cards/Stake.tsx
- src/components/cards/Stream.tsx
- src/components/homeTabs/GIVbacks.tsx
- src/components/homeTabs/GIVfarm.tsx
- src/components/homeTabs/GIVgarden.tsx
- src/components/homeTabs/GIVstream.tsx
- src/components/menu/RewardMenu.tsx
- src/components/modals/APR.tsx
- src/components/modals/GIVdropHarvestModal.tsx
- src/components/modals/HarvestAll.tsx
- src/components/modals/V3Stake.tsx
- src/components/modals/WhatisStream.tsx
- src/context/tokenDistro.context.tsx
- src/features/subgraph/subgraph.thunks.ts
- src/helpers/time.ts
- src/hooks/useGIVTokenDistroHelper.tsx
- src/hooks/useRegenTokenDistroHelper.tsx
> Move token distro helper to redux

- src/components/views/userPublicProfile/UserPublicProfile.view.tsx
Fixed the issue in staging related to not showing users public view
@divine-comedian
> Fixed User public view issue

- src/components/AmountInput.tsx
- src/components/cards/BaseStakingCard.tsx
- src/components/cards/Stake.tsx
- src/components/homeTabs/GIVfarm.tsx
- src/components/modals/HarvestAll.tsx
- src/config/development.ts
- src/config/production.ts
- src/features/subgraph/subgraph.types.ts
- src/helpers/networkProvider.ts
- src/hooks/useLiquidityPositions.tsx
- src/hooks/useStakingNFT.tsx
- src/lib/contracts.ts
- src/lib/stakingPool.ts
- src/lib/subgraph/subgraphDataTransform.ts
- src/lib/subgraph/subgraphQueryBuilder.ts
- src/types/config.ts
- src/types/subgraph.ts
Some refactoring of farms configuration
> Support gnosis GIV/DAI farm

- src/components/modals/HarvestAll.tsx
> fix givback double calc

- src/apollo/gql/gqlPurpleList.ts
- src/apollo/types/gqlTypes.ts
- src/components/views/donate/CryptoDonation.tsx
- src/components/views/donate/GIVBackToast.tsx
- src/components/views/donate/helpers.tsx
- src/hooks/usePurpleList.tsx
- src/lib/helpers.ts
- src/services/donation.ts
> show error on fail saving donation

- src/apollo/gql/gqlPurpleList.ts
- src/apollo/types/gqlTypes.ts
- src/components/views/donate/CryptoDonation.tsx
- src/components/views/donate/GIVBackToast.tsx
- src/hooks/usePurpleList.tsx
> fix donating from a purple list address fails to trigger GIVbacks warning

- src/lib/metamask/index.ts
> Support other tokens image in add token

- src/components/controller/modal.ctrl.tsx
> close welcome modal on user sign in

- src/components/views/project/ProjectDonateCard.tsx
- src/components/views/project/SimilarProjects.tsx
> fix scroll to similar projects on project donate card

- src/components/RadioButton.tsx
- src/components/homeTabs/GIVfarm.tsx
- src/components/views/donate/DonationTypes.tsx
- src/components/views/verification/ProjectRegistry.tsx
Changed the default selected value of ProjectRegistry
> Made Project Registery default not_selected

- src/components/views/verification/CheckCircle.tsx
- src/components/views/verification/ContentSelector.tsx
- src/components/views/verification/Done.tsx
- src/components/views/verification/VerificationIndex.tsx
> verification done step

- src/components/GeneralCard.sc.tsx
- src/components/styled-components/Position.ts
- src/components/views/join/JoinEngage.tsx
- src/components/views/join/JoinSubscriptionCard.tsx
- src/lib/constants/links.ts
> Add Community Call to Join page

- src/config/production.ts
Configured cult regen farm mainnet config based on this doc
https://www.notion.so/giveth/CULT-ETH-82128022373f426d9a224055288eead0
> CULT regen farm config

- src/components/GIVfrens.tsx
- src/config/development.ts
- src/types/config.ts
> Fix regenfarm

- src/components/views/project/ProjectDonationTable.tsx
> change dollar sign with USD

- src/helpers/requests.ts
Ref. #[525](https://github.com/Giveth/impact-graph/pull/525)
> add authVersion to gql

- src/components/modals/FailedDonation.tsx
- src/lib/constants/links.ts
> some changes on donation failed messages

- package.json
- src/components/views/homepage/HomeGetUpdates.tsx
- src/components/views/join/JoinSubscriptionCard.tsx
- src/hooks/useNewsletterSubscription.ts
- yarn.lock
> added new newsletter

- src/components/modals/ModalHeader.tsx
> Fix close modal color

- src/config/development.ts
- src/config/production.ts
[Ref.](https://developers.gnosischain.com/for-developers/developer-resources/update-rpc-url)
> fix production and dev nodeUrl config

- src/components/views/verification/ContentSelector.tsx
- src/components/views/verification/Loading.tsx
- src/context/verification.context.tsx
- src/lib/verification.ts
add loading in first step of verification
> Add loading to verification

- src/components/modals/HarvestAll.sc.tsx
- src/components/modals/HarvestAll.tsx
> Fix harvest modal first view

- pages/donate/[slug].tsx
- pages/index.tsx
- pages/project/[projectIdSlug]/index.tsx
- pages/projects.tsx
- pages/user/[address].tsx
> redirect to maintenance route if server has problem

- src/apollo/gql/gqlProjects.ts
- src/components/VerificationBadge.tsx
- src/components/styled-components/Badge.ts
- src/components/views/project/ProjectIndex.tsx
- src/components/views/project/projectDonateCard/ProjectDonateCard.tsx
- src/components/views/project/projectDonateCard/VerificationStatus.tsx
- src/components/views/userPublicProfile/projectsTab/ListingBadge.tsx
- src/components/views/userPublicProfile/projectsTab/ProjectsTable.tsx
> add verification status in single project card

- src/apollo/apolloClient.ts
- src/helpers/requests.ts
- src/lib/constants/links.ts
> change report issue link

- package.json
- src/components/Input.tsx
- src/components/modals/EditUserModal.tsx
- src/components/views/onboarding/InfoStep.tsx
- src/components/views/onboarding/PhotoStep.tsx
- src/components/views/onboarding/common.tsx
- yarn.lock
- #950 
@mateodaza @RamRamez @alireza-sharifpour I'm eager to know your comments about this.
> Use react hook form

- src/config/production.ts
- src/features/subgraph/subgraph.types.ts
- src/lib/subgraph/subgraphDataTransform.ts
- src/lib/subgraph/subgraphQueryBuilder.ts
Removed unused `uniswapV2EthGivPair` from query
> Fixed subgraph endpoint wrong value

- src/components/views/project/ProjectDonationTable.tsx
- src/components/views/userPublicProfile/donationsTab/DonationsTable.tsx
Ref. [Figma](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=4393%3A112100)
> remove USD sign from donation tables

- src/components/Input.tsx
- src/components/modals/EditUserModal.tsx
- src/components/views/onboarding/InfoStep.tsx
- src/components/views/verification/ProjectRegistry.tsx
- src/components/views/verification/common.types.ts
- src/components/views/verification/projectContact/AddSocialModal.tsx
- src/components/views/verification/projectContact/ProjectContactIndex.tsx
- src/components/views/verification/projectContact/common.tsx
- src/components/views/verification/projectContact/common.types.ts
- src/lib/constants/regex.ts
> add new form validation to project contact

- src/components/views/verification/PersonalInfo.tsx
> Add email default value

- src/components/DescriptionInput.tsx
- src/components/Input.tsx
- src/components/styled-components/TextArea.ts
- src/components/views/verification/Milestones.tsx
- src/components/views/verification/ProjectRegistry.tsx
- src/components/views/verification/manageFunds/ManageFundsIndex.tsx
- src/hooks/useFormValidation.tsx
- src/lib/constants/regex.ts
- src/types/inputValidation.ts
Ref. #997 
add description validation to manage funds
add description validation to milestones
add validation to project registry
> Verification/ add error styles to text area component

- src/components/views/project/ProjectDonationTable.tsx
- src/components/views/userPublicProfile/donationsTab/DonationsTable.tsx
> add dollar sign to donation tables

- src/apollo/types/types.ts
- src/components/views/create/CreateProject.tsx
- src/helpers/createProjectValidation.ts
> some fixes for multi addresses in create project

- src/apollo/apolloClient.ts
> show sign in wallet if token expired

- src/components/controller/modal.ctrl.tsx
- src/components/modals/FirstWelcomeModal.tsx
- src/components/modals/WalletModal.tsx
- src/lib/localStorage.ts
> Show first welcome modal once

- src/hooks/useDetectDevice.tsx
> fix widths to match our media queries

- src/apollo/gql/gqlProjects.ts
- src/apollo/types/gqlTypes.ts
- src/components/views/donate/helpers.tsx
- src/lib/constants/tokens.ts
- src/lib/contracts.ts
> Sort tokens

- src/components/views/create/CreateProject.tsx
> fix wallet address req error

- src/components/views/donate/CryptoDonation.tsx
- src/components/views/donate/InputBox.tsx
- src/components/views/donate/TokenPicker.tsx
> disabled donation token list dropdown when not connected

- src/components/views/verification/BeforeStart.tsx
> Added BeforeStart new text

- src/components/modals/Lock/LockingBrief.tsx
- src/components/modals/LockupDetailsModal.tsx
- src/features/subgraph/subgraph.services.ts
- src/features/subgraph/subgraph.slice.ts
- src/features/subgraph/subgraph.types.ts
- src/helpers/givpower.ts
- src/lib/subgraph/subgraphDataTransform.ts
- src/lib/subgraph/subgraphQueryBuilder.ts
- src/types/subgraph.ts
> Integrate subgraphs

- src/components/modals/Modal.tsx
- src/hooks/useDeviceDetect.tsx
> Fix modal shift

- src/components/views/project/ProjectTimeline.tsx
- src/components/views/project/ProjectUpdates.tsx
> Updated ProjectUpdates and ProjectTimeline Texts

- src/components/cards/BaseStakingCard.tsx
- src/components/cards/Stake.tsx
- src/components/homeTabs/GIVfarm.tsx
- src/config/development.ts
- src/types/config.ts
Allowed users to harvest their reward on archived farms
[#653 ](https://github.com/Giveth/GIVeconomy/issues/653#event-6928475165)
> Added archive feature to farms

- src/components/RichTextInput.tsx
- src/components/RichTextViewer.tsx
- src/components/modals/GoodProjectDescription.tsx
- src/components/views/project/ProjectTimeline.tsx
> Update text area should have expand limit

- src/components/modals/Modal.tsx
> fixed modal shift layour issue (dynamic import)

- src/components/modals/DonateModal.tsx
> add loading to donate modal button

- src/components/views/verification/menu/DesktopMenu.tsx
- src/components/views/verification/menu/MenuModal.tsx
- src/components/views/verification/menu/MobileMenu.tsx
- src/lib/verification.ts
1. bind checked steps to last step in DB
2. prevent user to select any steps on mobile
> Verification/bind checked steps to DB

- src/components/modals/StakeLock/StakeGIV.tsx
> add blockscout external link icon

- src/components/modals/GoodProjectDescription.tsx
> Browse examples open in new tab

- src/components/cards/BaseStakingCard.tsx
- src/components/modals/LockupDetailsModal.tsx
- src/helpers/givpower.ts
- src/lib/stakingPool.ts
- src/lib/subgraph/subgraphDataTransform.ts
- src/types/subgraph.ts
> GIVpower dynamic APR

- src/components/cards/BaseStakingCard.tsx
- src/components/modals/LockupDetailsModal.tsx
- src/components/modals/StakeLock/LockSlider.tsx
- src/helpers/givpower.ts
- src/lib/stakingPool.ts
- src/lib/subgraph/subgraphDataTransform.ts
- src/types/subgraph.ts
> Show unlock date after slider change

- src/components/views/verification/ProjectRegistry.tsx
- src/components/views/verification/VerificationIndex.tsx
1. add fade-In animation to registration
2. add fade-In animation when steps are changing
> add fade-In animation to verification

- package.json
- src/components/cards/BaseStakingCard.tsx
- src/config/production.ts
> Active harvest on archived farms

- src/components/views/join/JoinEngage.tsx
> changed join title

- src/components/views/verification/manageFunds/AddAddressModal.tsx
> Update add wallet title

- src/apollo/gql/gqlVerification.ts
- src/apollo/types/types.ts
- src/components/FileUploader.tsx
- src/components/views/verification/Milestones.tsx
- src/components/views/verification/ProjectRegistry.tsx
- src/helpers/file.ts
> use FileUploader

- src/components/cards/BaseStakingCard.tsx
@MohammadPCh #1154 seems fine, just made this PR to improve user experience
> Optimized open staking card directly

- src/components/cards/BaseStakingCard.tsx
- src/components/modals/Stake.tsx
- #1145 
try it out like this:
/givfarm?open=`[StakeingType]`&chain=`[chainId]`
staking types:
- UniswapV2_GIV_DAI
- UniswapV3
- Balancer
- Sushiswap
- Honeyswap_GIV_HNY
- Honeyswap_GIV_DAI
- GIV_LM
- Honeyswap_FOX_HNY
- UniswapV2_CULT_ETH
chains:
- gnosis
- main
so if you want to show the GIV stake modal on Gnosis, the address will be something like this:
/givfarm?open=GIV_LM&chain=gnosis
> open stake modal by query param

- src/components/modals/StakeLock/StakeGIV.tsx
> fix blockscout typo

- src/components/modals/StakeLock/Lock.tsx
- src/components/modals/StakeLock/LockInfo.tsx
- src/components/modals/StakeLock/LockingBrief.tsx
- src/components/modals/StakeLock/StakeGIV.tsx
- yarn.lock
> Make givpower ready for launch

- src/components/views/create/CreateProject.tsx
Ref. #1155 
To avoid conflicts, this PR should be merged after merging PR #1135
> fix #1155 some improvements on create project page

- src/components/views/project/projectDonateCard/VerificationStatus.tsx
Ref. #922
1. remove 'please contact support' for verified projects
2. change verify status to verification status
3. change contact support text
> fix 922 verification badge

- src/components/modals/GoodProjectDescription.tsx
- src/lib/constants/links.ts
> fix how to write fundraising Project link

- src/components/cards/BaseStakingCard.tsx
> Fix apr range display condition

- src/components/cards/BaseStakingCard.tsx
- src/helpers/networkProvider.ts
> show default staking card for giv on mainnet

- src/components/views/project/ProjectIndex.tsx
> fix showing blank page when wallet is not connected

- src/components/views/create/CreateProject.tsx
- src/components/views/create/WalletAddressInput.tsx
- src/components/views/onboarding/InfoStep.tsx
- src/components/views/verification/manageFunds/AddAddressModal.tsx
- src/lib/constants/regex.ts
- src/lib/wallet.ts
> some fixes for multi recipient

- src/components/modals/StakeLock/Lock.tsx
- src/components/modals/StakeLock/LockSlider.tsx
> Make default round zero

- src/components/ImageUploader.tsx
- src/components/modals/EditUserModal.tsx
- src/components/views/create/CreateProject.tsx
- src/components/views/create/imageInput/ImageInput.tsx
- src/components/views/onboarding/PhotoStep.tsx
> fix Not properly refreshing the removed image in create project

- src/components/views/projects/ProjectsBanner.tsx
- src/components/views/projects/ProjectsIndex.tsx
> Fixed categories responsive issues

- src/components/cards/BaseStakingCard.tsx
- src/components/homeTabs/GIVpower.tsx
- src/components/modals/StakeLock/LockSlider.tsx
- src/components/modals/StakeLock/LockingBrief.tsx
- src/features/subgraph/subgraph.types.ts
- src/helpers/givpower.ts
- src/lib/subgraph/subgraphDataHelper.ts
- src/lib/subgraph/subgraphDataTransform.ts
- src/lib/subgraph/subgraphQueryBuilder.ts
- src/types/subgraph.ts
Fixed Subgraph GIVPower data transformation
Some refactoring
> Merge GIVeconomy Merge

- src/components/views/verification/common.tsx
progress-bar width should be full when form is submitted
> verification / fix progress-bar width

- src/components/views/verification/TermsAndConditions.tsx
- src/context/verification.context.tsx
1. force to send data on terms step
2. when submitting form on last step, show error instead of showing done page
> verification / force to send data on terms step

- src/components/modals/StakeLock/StakeGIV.tsx
> Fix giv stake tx link

- src/components/cards/BaseStakingCard.sc.tsx
- src/components/cards/BaseStakingCard.tsx
> Add lockup modal to staking card

- src/components/IconWithToolTip.tsx
- src/components/modals/LockupDetailsModal.tsx
> Add lockup modal tooltips

- src/lib/subgraph/subgraphQueryBuilder.ts
> fix getTokenLocksInfoQuery

- src/components/views/about/AboutMission.tsx
- src/components/views/create/CreateProject.tsx
- src/components/views/homepage/HomeHeader.tsx
- src/lib/constants/links.ts
updated the homepage header links as per 
https://github.com/Giveth/giveth-dapps-v2/issues/1058#issue-1293643021
> update homepage header links

- src/components/controller/subgraph.ctrl.tsx
- src/features/subgraph/subgraph.services.ts
- src/features/subgraph/subgraph.thunks.ts
- src/features/subgraph/subgraph.types.ts
- src/hooks/useStakingPool.tsx
- src/lib/stakingPool.ts
- src/lib/subgraph/subgraphQueryBuilder.ts
fix:
- #1173 
Please first review and merge this: #1223 
Thanks
> Add default apr

- src/components/controller/subgraph.ctrl.tsx
- src/features/subgraph/subgraph.services.ts
- src/features/subgraph/subgraph.thunks.ts
- src/features/subgraph/subgraph.types.ts
- src/lib/subgraph/subgraphQueryBuilder.ts
> get subgraph data even no connected wallet

- src/helpers/requests.ts
Fixed issue when backend returns 200 but there is an error.
> fixed transformGraphQLErrorsToStatusCode error handling

- src/components/cards/BaseStakingCard.tsx
- src/components/cards/Govern.tsx
- src/components/cards/Stake.tsx
- src/hooks/useLiquidityPositions.tsx
- src/hooks/useStakingPool.tsx
- src/lib/stakingPool.ts
- src/types/poolInfo.ts
Made APR datatype to an object containing `effectiveAPR` and `vaultIRR` to support angel vault double APR
Ref #1228
> Change APR datatype

- src/components/IconWithToolTip.tsx
- src/components/cards/BaseStakingCard.sc.tsx
- src/components/cards/BaseStakingCard.tsx
> Add angel vault apr tooltip

- src/lib/stakingPool.ts
Fetch unipool info from the chain in case subgraph fetch was not successful
> Fetch unipool info from chain

- src/components/cards/Govern.tsx
- src/hooks/useStakingPool.tsx
- src/lib/stakingPool.ts
Moved fetching unipool info to a function for all APR calculation
> Refactor unipool info fetching in APR calculation

- package.json
- src/components/menu/FilterMenu.tsx
- yarn.lock
> Fix most funded icon

- src/components/homeTabs/GIVbacks.tsx
- src/components/homeTabs/commons.tsx
based on @divine-comedian requests on the All-dev channel.
> Fix givbacks responsiveness

- src/artifacts/GivPower.json
- src/artifacts/UnipoolTokenDistributor.json
- src/lib/stakingPool.ts
Reverted wrong changes on UnipoolTokenDistributor.json
Refs #1285
> Add GivPower ABI

- src/components/cards/BaseStakingCard.sc.tsx
- src/components/cards/BaseStakingCard.tsx
features requested in https://github.com/Giveth/giveth-dapps-v2/issues/1188
> Locked icon tooltip

- src/components/cards/BaseStakingCard.sc.tsx
- src/components/cards/BaseStakingCard.tsx
updating apr tooltips as per
https://github.com/Giveth/giveth-dapps-v2/issues/1228
> add tooltip and flex

- package.json
- yarn.lock
> hotfix - update quill

- src/components/cards/GIVpowerCardIntro.tsx
- src/components/modals/LockupDetailsModal.tsx
> add LockupDetailsModal to GIVpowerCardIntro

- src/components/homeTabs/GIVpower.sc.tsx
- src/components/homeTabs/GIVpower.tsx
> Fix givpower reward card

- src/components/modals/StakeLock/StakeGIV.tsx
> remove cancel button

- src/components/cards/BaseStakingCard.tsx
- src/components/cards/Govern.tsx
- src/components/homeTabs/GIVfarm.tsx
- src/components/modals/BridgeGIV.tsx
- src/components/modals/ModalHeader.tsx
- src/components/modals/StakeLock/TotalGIVpowerBox.tsx
- src/context/givpower.context.tsx
- src/helpers/networkProvider.ts
- src/hooks/useStakingPool.tsx
- src/lib/constants/links.ts
- src/lib/stakingPool.ts
> Show bridge modal on mainnet

- src/lib/subgraph/subgraphQueryBuilder.ts
> order By unlockableAt

- src/components/cards/BaseStakingCard.tsx
- src/helpers/givpower.ts
> Fix average apr

- src/components/views/projects/ProjectsMainCategories.tsx
Swipe to selected MainCategory
> fixed selected maincategory visibility issue

- src/components/modals/Unstake/UnStake.tsx
> use stakedAmount instead of maxAmount

- src/components/modals/Unstake/UnStake.tsx
> Disable lockup button on unstake modal

- src/components/modals/StakeLock/Lock.tsx
- src/components/modals/StakeLock/LockInfo.tsx
> Add rounds tooltip

- src/components/cards/BaseStakingCard.tsx
> Add givpower apr tooltip

- src/components/views/projects/ProjectsIndex.tsx
> Fixed LoadMore Issue

- src/components/RewardCard.tsx
- src/components/modals/WrongNetwork.tsx
- src/components/modals/WrongNetworkInnerModal.tsx
> Fix wrong inner modal

- src/components/homeTabs/GIVpower.tsx
> Made givpower titles coming soon

- src/components/views/verification/manageFunds/AddAddressModal.tsx
- src/components/views/verification/manageFunds/SelectNetwork.tsx
Ref. #1181 
1. fix duplicate address check
2. show pointer cursor on select items
> Hotfix verification duplicate address check

- src/components/views/project/projectDonateCard/ProjectDonateCard.tsx
Ref. #1304
Add some drag constraints to donate card in project page
> fix donate card responsive issue

- src/lib/subgraph/subgraphQueryBuilder.ts
> Fixed query builder issue on mainnet

- src/components/views/project/SimilarProjects.tsx
> similar projects bug

- src/components/Checkbox.tsx
- src/components/GeneralCard.sc.tsx
- src/components/views/donate/ProjectCardSelector.tsx
1. add gray bar in mobile view to project card in donate page
2. fix font weight of join page titles
3. fix font size of checkboxes
> Some tiny fixes

- src/components/notification/NotificationBox.tsx
- src/components/views/notification/notification.view.tsx
- src/helpers/html.tsx
> Add unread indicator to notification box

- pages/_app.tsx
- pages/api/notif.js
- src/components/controller/notification.ctrl.tsx
- src/configuration.ts
- src/features/notification/notification.services.ts
- src/features/notification/notification.slice.ts
- src/features/notification/notification.thunks.ts
- src/features/notification/notification.types.ts
- src/features/store.ts
- src/lib/constants/Routes.ts
- src/types/config.ts
> Add notification slice

- src/components/styled-components/Tabs.ts
- src/components/views/notification/notification.view.tsx
- src/components/views/userPublicProfile/PublicProfileContributes.tsx
- src/features/notification/notification.slice.ts
> Add notification page tab

- src/components/Header/Header.tsx
- src/components/notification/NotificationBox.tsx
- src/components/notification/NotificationMenu.tsx
- src/components/views/notification/notification.view.tsx
- src/helpers/html.tsx
- src/lib/helpers.ts
> Add notification time

- src/components/notification/NotificationMenu.tsx
> fixed notification Link issue

- src/components/project-card/ProjectCard.tsx
> Added givpower to porject cards

- pages/test.tsx
- src/components/modals/Boost/BoostModal.tsx
- src/lib/constants/Routes.ts
> Add boost modals

- src/components/givfarm/DAOChangeNetworkModal.tsx
- src/components/modals/APR.tsx
- src/components/modals/Modal.tsx
- src/components/modals/SkipOnboardingModal.tsx
- src/components/modals/StakeLock/StakeLock.sc.tsx
- src/components/modals/UNIv3APR.tsx
- src/components/modals/Unstake/UnStake.tsx
- src/components/modals/WrongNetworkInnerModal.tsx
> Improve modal

- src/components/Checkbox.tsx
- src/components/views/create/CategoryInput.tsx
> Fix create project categories styles

- src/components/modals/LockupDetailsModal.tsx
- src/components/styled-components/Table.tsx
- src/components/views/project/projectDonations/ProjectDonationTable.tsx
- src/components/views/userProfile/ProfileContributeCard.tsx
- src/components/views/userProfile/ProfileContributes.tsx
- src/components/views/userProfile/boostedTab/ProfileBoostedTab.tsx
- src/components/views/userProfile/common.sc.tsx
- src/components/views/userProfile/donationsTab/DonationsTable.tsx
- src/components/views/userProfile/donationsTab/ProfileDonationsTab.tsx
- src/components/views/userProfile/projectsTab/ProfileProjectsTab.tsx
- src/components/views/userProfile/projectsTab/ProjectsTable.tsx
> Add my boosted projects tab

- package.json
- src/components/RichTextViewer.tsx
- src/components/badges/ShareLikeBadge.tsx
- src/components/views/project/ProjectIndex.tsx
- src/components/views/project/ProjectTabs.tsx
- src/components/views/project/projectDonateCard/ProjectDonateCard.tsx
- src/components/views/project/projectGIVPower/GIVPowerHeader.tsx
- src/components/views/project/projectGIVPower/GIVPowerTable.tsx
- src/components/views/project/projectGIVPower/NoBoost.tsx
- src/components/views/project/projectGIVPower/index.tsx
- yarn.lock
> Adding boost to single project view

- src/components/project-card/ProjectCard.tsx
> update projectcard design for givpower

- package.json
- src/components/NotAvailableProject.tsx
- src/components/views/project/SimilarProjects.tsx
- yarn.lock
> Add swiper to similar projects

- next.config.js
- src/apollo/gql/gqlProjects.ts
- src/apollo/gql/gqlUser.ts
- src/components/project-card/ProjectCard.tsx
- src/components/views/homepage/HomeExploreProjects.tsx
- src/components/views/projects/ProjectsIndex.tsx
- src/components/views/userPublicProfile/PublicProfileLikedTab.tsx
- src/components/views/userPublicProfile/projectsTab/PublicProfileProjectsTab.tsx
> fix Some issues on project donate card

- package.json
- src/components/Footer/Footer.tsx
- yarn.lock
> Added discord to footer

- src/components/menu/FilterMenu.tsx
- src/components/views/projects/ProjectsFiltersButton.tsx
- src/components/views/projects/ProjectsIndex.tsx
1. fix project cards wrapper padding
2. add fade out animation to filter modal
> two fixes on Categories develop branch

- package.json
- src/components/Checkbox.tsx
- src/components/menu/FilterMenu.tsx
- yarn.lock
Remove sort by from filters and add reset filters to filters modal
> Categories develop branch remove sortby

- src/components/views/create/CreateProject.tsx
- src/components/views/create/WalletAddressInput.tsx
> Remove caption when address is correct

- src/components/modals/Boost/BoostInnerModal.tsx
- src/components/modals/Boost/BoostModal.tsx
- src/components/views/project/projectDonateCard/ProjectDonateCard.tsx
> 761 givpower boosting functionality

- src/components/modals/Boost/BoostInnerModal.tsx
> added setFinalPercentage

- src/components/modals/Boost/BoostInnerModal.tsx
> handled when the boosting project has already boosted

- pages/account.tsx
- pages/onboard.tsx
- pages/verification/[slug]/[token].tsx
- pages/verification/[slug]/index.tsx
- src/components/CompleteProfile.tsx
- src/components/UserNotSignedIn.tsx
- src/components/WalletNotConnected.tsx
- src/components/views/EditIndex.tsx
- src/components/views/create/CreateIndex.tsx
- src/components/views/create/CreateProject.tsx
- src/components/views/create/SuccessfulCreation.tsx
- src/components/views/onboarding/Onboarding.view.tsx
- src/components/views/verification/EmailVerificationIndex.tsx
[#1079 ](https://github.com/Giveth/giveth-dapps-v2/issues/1079#issuecomment-1237341230)
> Implement user not signed in design

- src/apollo/gql/gqlPowerBoosting.ts
- src/components/modals/Boost/BoostInnerModal.tsx
- src/components/modals/Boost/DeletePowerBoostModal.tsx
- src/components/views/userProfile/boostedTab/BoostsTable.tsx
- src/components/views/userProfile/boostedTab/ProfileBoostedTab.tsx
> Add power boosting management back-end

- src/components/controller/user.ctrl.tsx
> sign out user automatically when user wallet is changed

- package.json
- src/components/Accordion.tsx
- src/components/GeneralCard.sc.tsx
- src/components/project-card/ProjectCard.tsx
- src/components/views/FAQIndex.tsx
- src/components/views/TermsIndex.tsx
- src/components/views/about/AboutIndex.tsx
- src/components/views/create/Guidelines.tsx
- src/components/views/homepage/HomeBlogPost.tsx
- src/components/views/homepage/HomeChangeMakers.tsx
- src/components/views/homepage/HomeFromBlog.tsx
- src/components/views/join/JoinIndex.tsx
- src/components/views/partnerships/PartnershipsIndex.tsx
- src/components/views/projects/ProjectsIndex.tsx
- src/components/views/userPublicProfile/projectsTab/ProjectsTable.tsx
- styles/globals.css
- yarn.lock
Related to PR [#68](https://github.com/Giveth/ui-design-system/pull/68)
1. fix button color on about page
2. make accordion header unselectable
3. fix faq padding and title z-index on mobile
4. center align support card
5. make Submission guidelines card unselectable
6. convert script tags in blog posts title to text
7. fix Changemakers title and text alignment in mobile
8. fix FROM OUR BLOG title font type
9. fix Join our Community font size on mobile
10. update @giveth/ui-design-system
11. fix Partnerships font size on mobile
12. fix project card updated at position on mobile
13. fix projects title going under arc
14. fix waiting for review not showing correctly on mobile
15. fix Terms of use wrapper responsive margin and padding
> fix mobile font size issue

- src/apollo/gql/gqlPowerBoosting.ts
- src/apollo/gql/gqlProjects.ts
- src/apollo/types/types.ts
- src/components/views/project/ProjectIndex.tsx
- src/components/views/project/ProjectTabs.tsx
- src/components/views/project/projectGIVPower/GIVPowerTable.tsx
- src/components/views/project/projectGIVPower/index.tsx
> 762 project boostings

- src/components/Input.tsx
- src/components/views/userProfile/boostedTab/BoostsTable.tsx
> Fix boost manage

- src/components/modals/Boost/DeletePowerBoostModal.tsx
- src/components/views/project/projectDonateCard/ProjectDonateCard.tsx
- src/components/views/project/projectGIVPower/NoBoost.tsx
- src/components/views/userProfile/ProfileContributes.tsx
- src/components/views/userProfile/boostedTab/BoostsTable.tsx
- src/components/views/userProfile/boostedTab/ProfileBoostedTab.tsx
> text and styling imrpovements updates

- src/components/views/project/projectGIVPower/GIVPowerTable.tsx
- src/components/views/project/projectGIVPower/index.tsx
> 762 project boostings pagination

- src/apollo/gql/gqlPowerBoosting.ts
- src/apollo/types/types.ts
- src/components/views/project/projectGIVPower/GIVPowerTable.tsx
- src/components/views/project/projectGIVPower/index.tsx
> 761 add user rank

- src/components/modals/Boost/ApprovePowerBoostModal.tsx
- src/components/modals/Boost/DeletePowerBoostModal.tsx
- src/components/views/userProfile/boostedTab/BoostsTable.tsx
add approve modal to the GIVpower boosting management
- #758
> Add approve modal to the boosting management

- src/components/views/project/projectGIVPower/GIVPowerHeader.tsx
- src/components/views/project/projectGIVPower/GIVPowerTable.tsx
> 761 added to fixed to table amount

- src/components/views/projects/ProjectsSubCategories.tsx
> 1122 replace subcategories value with name

- src/components/cards/BaseStakingCard.tsx
> remove GIVgarden from title

- src/config/development.ts
Quick note: Both APR in goerli and gnosis are in 0% is this good behavior?
> Giveth gnosis hosted subgraph for develop env

- src/components/views/userProfile/boostedTab/BoostsTable.tsx
> fixed booststable icon issue

- package.json
- src/components/modals/HarvestAll.sc.tsx
- src/components/modals/HarvestAll.tsx
- src/components/modals/LockupDetailsModal.tsx
- src/components/modals/Unstake/UnStake.tsx
- src/components/modals/WhatisStream.tsx
- styles/globals.css
- yarn.lock
> Fix givpower responsiveness

- tsconfig.json
> Resolved cypress and jest conflict

- pages/onboard.tsx
- src/components/modals/SkipOnboardingModal.tsx
- src/components/views/onboarding/AlreadyRegistered.tsx
- src/components/views/onboarding/InfoStep.tsx
- src/components/views/onboarding/Onboarding.view.tsx
- src/components/views/onboarding/PhotoStep.tsx
- src/components/views/onboarding/common.tsx
> fix User profile information not displayed on onboarding

- src/components/homeTabs/GIVbacks.tsx
- src/hooks/useGIVTokenDistroHelper.tsx
> Change rounds time

- src/components/homeTabs/GIVpower.sc.tsx
- src/components/homeTabs/GIVpower.tsx
- src/components/modals/LockupDetailsModal.tsx
> fix boosting styles

- pages/onboard.tsx
- src/components/menu/MenuWallet.tsx
- src/components/menu/RewardMenu.tsx
- src/components/modals/SkipOnboardingModal.tsx
- src/components/views/onboarding/AlreadyRegistered.tsx
- src/components/views/onboarding/InfoStep.tsx
- src/components/views/onboarding/Onboarding.view.tsx
- src/components/views/onboarding/PhotoStep.tsx
- src/components/views/onboarding/common.tsx
- src/config/development.ts
- tsconfig.json
> Merge develop to categories

- src/config/development.ts
Set giveth default xdai staging subgraph in development.ts
> staging xdai subgraph

- src/config/development.ts
We need to use test deployment 6 in givpower
> use deployment six in givpower

- src/components/cards/BaseStakingCard.sc.tsx
- src/components/cards/BaseStakingCard.tsx
[#722](https://github.com/Giveth/GIVeconomy/issues/722)
> GIVpower Staking Card Tooltip update

- src/components/homeTabs/GIVpower.sc.tsx
- src/components/homeTabs/GIVpower.tsx
> fix your givpower card and copy

- src/components/views/project/ProjectIndex.tsx
- src/components/views/project/projectGIVPower/GIVPowerHeader.tsx
- src/components/views/project/projectGIVPower/NoBoost.tsx
- src/components/views/project/projectGIVPower/index.tsx
> 762 fix givpower issues

- src/config/production.ts
switch to temporary production xdai subgraph to test givpower
> givpower production subgraph

- src/components/homeTabs/GIVpower.sc.tsx
- src/components/homeTabs/GIVpower.tsx
> add stake for givpower button

- src/components/NetworkSelector.tsx
- src/components/homeTabs/GIVbacks.sc.tsx
- src/components/homeTabs/GIVfarm.sc.tsx
- src/components/homeTabs/GIVgarden.sc.tsx
- src/components/homeTabs/GIVpower.sc.tsx
- src/components/homeTabs/GIVstream.sc.tsx
- src/components/homeTabs/GIVstream.tsx
- src/components/homeTabs/commons.tsx
- src/components/modals/StakeLock/Lock.tsx
> Giveconomy responsiveness

- src/components/modals/Boost/BoostInnerModal.tsx
> handle max 20 boosted projects

- src/components/views/project/projectGIVPower/NoBoost.tsx
> Fixed PM View Text

- src/components/views/userProfile/boostedTab/BoostsTable.tsx
- src/components/views/userProfile/boostedTab/ProfileBoostedTab.tsx
- src/helpers/givpower.ts
fix these issues:
- problem on edit when the user only has one boost (#758)
- fix boost table performance
- handle sort boosts on front-end
> Some fixes on boosts table

- src/components/modals/Boost/BoostInnerModal.tsx
- src/components/modals/Boost/BoostModal.sc.tsx
- src/components/modals/Boost/BoostModal.tsx
> 1599 handle boost limit

- src/components/menu/FilterMenu.tsx
> added Accept Funds on Gnosis

- src/components/views/project/projectGIVPower/NoBoost.tsx
> fixed typo

- src/components/modals/LockupDetailsModal.tsx
> fix cells and header width

- src/components/cards/BaseStakingCard.tsx
> disable lock button if userNotStakedAmount is zero

- src/components/cards/BaseStakingCard.tsx
> Fix available to staked token

- src/components/cards/BaseStakingCard.tsx
- src/components/modals/LockupDetailsModal.tsx
> Fix lockup detail table header

- src/components/views/project/ProjectIndex.tsx
- src/components/views/project/ProjectUpdates.tsx
- src/components/views/project/SimilarProjects.tsx
> some issues on similar projects

- src/components/views/userProfile/ProfileContributes.tsx
- src/lib/constants/Routes.ts
> fix public profile not showing donations nor liked projects

- src/components/badges/CategoryBadge.tsx
- src/components/views/project/projectDonateCard/ProjectDonateCard.tsx
> Fix category badge

- src/components/RegenFarm.tsx
- src/components/givfarm/GIVfrens.tsx
- src/components/homeTabs/GIVfarm.sc.tsx
- src/components/homeTabs/GIVfarm.tsx
- src/config/development.ts
> Handle regenfarms archive

- .vscode/settings.json
- src/components/modals/HarvestAll.tsx
- src/components/project-card/ProjectCard.tsx
- src/components/views/project/projectDonateCard/GIVbackToast.tsx
> Change GIVback to GIVbacks

- src/components/menu/FilterMenu.tsx
> change Accept GIV Token to Accept GIV

- src/components/views/project/projectGIVPower/NoBoost.tsx
- src/components/views/project/projectGIVPower/index.tsx
> Givpower boosting fix copy 

- src/components/modals/Boost/DeletePowerBoostModal.tsx
> Update delete boost modal copy

- src/components/modals/Boost/DeletePowerBoostModal.tsx
- src/components/views/userProfile/boostedTab/ProfileBoostedTab.tsx
- src/features/user/user.slice.ts
> Fix boosted projects count

- src/components/views/userProfile/boostedTab/BoostsTable.tsx
- src/components/views/userProfile/boostedTab/EmptyPowerBoosting.tsx
> Update my account boosting

- package.json
- src/components/modals/StakeLock/Stake.tsx
> Fix angel vault stake with permit

- src/components/notification/NotificationBox.tsx
- src/lib/constants/Routes.ts
> Fix notificationbox date

- package.json
- src/components/cards/BaseStakingCard.sc.tsx
- src/components/cards/BaseStakingCard.tsx
- src/config/development.ts
- src/config/production.ts
- src/helpers/networkProvider.ts
- src/types/config.ts
> HOTFIX: GIVfarm cleanup

- .vscode/settings.json
- package.json
- src/components/RegenFarm.tsx
- src/components/givfarm/GIVfrens.tsx
- src/components/homeTabs/GIVfarm.tsx
- src/config/production.ts
> Arhive fox honey farm

- src/components/views/notification/notification.view.tsx
- src/features/notification/notification.services.ts
- src/helpers/requests.ts
> Add notifications tab

- package.json
- src/content/Partnerships.ts
> 1742 remove partnerships

- pages/index.tsx
- src/apollo/gql/gqlOptions.ts
- src/apollo/gql/gqlProjects.ts
- src/components/menu/FilterMenu.tsx
- src/components/views/projects/ProjectsSortSelect.tsx
- src/context/projects.context.tsx
> 1736 make givpower sorting default sort

- package.json
- src/apollo/gql/gqlPowerBoosting.ts
- src/components/cards/BaseStakingCard.tsx
- src/components/toasts/index.tsx
- src/components/views/userProfile/boostedTab/BoostsTable.tsx
- yarn.lock
> 1740 hint unverified projects on boost table

- src/components/views/userProfile/boostedTab/BoostsTable.tsx
> Add tooltip to unlockable icons

- src/components/views/project/projectGIVPower/index.tsx
> 1766 add loading to givpower tab

- package.json
- src/components/homeTabs/GIVstream.tsx
> 1796 make givfarm default source

- src/components/notification/NotificationBox.tsx
- src/components/styled-components/Tabs.ts
- src/components/views/notification/notification.sc.tsx
- src/components/views/notification/notification.view.tsx
- src/helpers/html.tsx
> Fix notifications styling

- src/components/modals/Boost/BoostInnerModal.tsx
> 1802 update boosting modal

- package.json
- src/components/RegenFarm.tsx
- src/components/cards/BaseStakingCard.tsx
- src/components/cards/Stake.tsx
- src/components/homeTabs/GIVfarm.tsx
- src/config/development.ts
- src/config/production.ts
- src/lib/constants/constants.ts
- src/types/config.ts
> 1784 update GIVfarm states

- pages/test1.tsx
- src/components/IconWithToolTip.tsx
- src/components/Tooltip.tsx
fixed tooltips sizing on mobile
> Fix tooltip position

- src/components/Header/Header.tsx
> Changed number of shown notifications in menu

- package.json
- src/lib/claim.ts
> Fixed givderop claim query issue

- src/components/modals/Boost/BoostInnerModal.tsx
- src/components/modals/Boost/BoostModal.sc.tsx
> 1801 boost 100 percent

- src/components/cards/GIVpowerCardIntro.tsx
- src/components/modals/StakeLock/Lock.tsx
- src/components/modals/StakeLock/LockInfo.tsx
> 1822 update givpower card and lock modal

- src/components/views/notification/notification.view.tsx
> Handle notifications infinite scroll

- pages/project/[projectIdSlug]/index.tsx
- src/apollo/gql/gqlPowerBoosting.ts
- src/apollo/gql/gqlUser.ts
- src/apollo/types/types.ts
- src/components/views/project/projectDonations/ProjectWalletAddress.tsx
- src/components/views/project/projectGIVPower/GIVPowerTable.tsx
- src/components/views/project/projectGIVPower/index.tsx
> Show current booster in givpower tab

- package.json
- src/components/menu/FilterMenu.tsx
> 1845 quick fix typo

- src/components/FileUploader.tsx
- src/components/GIVpowerRank.tsx
- src/components/cards/BaseStakingCard.tsx
- src/components/cards/GIVpowerCardIntro.tsx
- src/components/project-card/ProjectCard.tsx
- src/components/styled-components/Flex.tsx
- src/components/views/project/projectDonateCard/ProjectDonateCard.tsx
- src/components/views/project/projectGIVPower/GIVPowerHeader.tsx
- src/components/views/project/projectGIVPower/NoBoost.tsx
> update Project card rank

- src/components/views/project/projectDonateCard/ProjectDonateCard.tsx
- src/components/views/project/projectGIVPower/index.tsx
> 1838 hide boost part in deative projects

- src/context/project.context.tsx
> fixed givpower value issue

- src/components/GIVpowerRank.tsx
> show current as next if not available

- src/components/ContributeCard.tsx
- src/components/views/userProfile/ProfileOverviewTab.tsx
- src/components/views/userProfile/boostedTab/ProfileBoostedTab.tsx
> 1775 change givpower contribute card

- package.json
- src/components/cards/BaseStakingCard.tsx
- src/config/production.ts
> fix non exploited farms copy

- package.json
- src/components/modals/DonateModal.tsx
> remove donation being processed toast when tx is mined

- src/components/animations/lottieControl.tsx
- src/components/cards/Congratulations.tsx
- src/components/cards/PositionCard.tsx
- src/components/modals/ConfirmSubmit.tsx
- src/components/modals/GIVdropHarvestModal.tsx
- src/components/modals/HarvestAll.tsx
- src/components/modals/StakeLock/Stake.tsx
- src/components/modals/StakeLock/TotalGIVpowerBox.tsx
- src/components/modals/V3Stake.tsx
- src/components/views/onboarding/DoneStep.tsx
- src/components/views/verification/EmailVerificationIndex.tsx
Update LottieControl from Class Component to Functional Component and make it LazyLoad for performance improvement.
Use LottieControl everywhere!
> Improve lottie

- .vscode/settings.json
- src/components/GIVpowerRank.tsx
- src/components/project-card/ProjectCardLikeAndShareButtons.tsx
> Update project projected rank

- src/components/GIVpowerRank.tsx
> fix projected rank

- src/components/views/project/projectGIVPower/GIVPowerTable.tsx
- src/components/views/project/projectGIVPower/index.tsx
- src/context/project.context.tsx
> Sort givpower table

- src/components/Header/Header.tsx
- src/components/controller/notification.ctrl.tsx
- src/components/views/notification/notification.sc.tsx
- src/components/views/notification/notification.view.tsx
- src/features/notification/notification.services.ts
- src/features/notification/notification.thunks.ts
> Update notification api and design

- pages/user/[address].tsx
- src/components/Header/Header.tsx
> remove cache form GET_USER_BY_ADDRESS

- src/components/modals/Boost/BoostInnerModal.tsx
- src/components/views/project/ProjectIndex.tsx
- src/context/project.context.tsx
> Calculate projected rank only for active projects

- package.json
- src/components/GIVpowerRank.tsx
- src/components/project-card/ProjectCard.tsx
- src/components/views/project/ProjectTabs.tsx
> First round fixes

- package.json
- src/components/modals/Boost/BoostInnerModal.tsx
- src/components/project-card/ProjectCardLikeAndShareButtons.tsx
- src/components/views/project/projectDonateCard/ProjectDonateCard.tsx
> Add boost button to project card

- package.json
- src/components/homeTabs/Overview.tsx
> Add givdrop end time

- lang/en.json
- lang/es.json
- src/components/project-card/ProjectCard.tsx
> change GIVback eligible copy

- pages/project/[projectIdSlug]/index.tsx
- src/components/modals/deactivateProject/DeactivateProjectIndex.tsx
- src/components/views/project/ProjectHeader.tsx
- src/components/views/project/ProjectIndex.tsx
- src/components/views/project/ProjectTabs.tsx
- src/components/views/project/ProjectUpdates.tsx
- src/components/views/project/projectDonateCard/ProjectDonateCard.tsx
- src/components/views/project/projectDonations/ProjectDonationTable.tsx
- src/components/views/project/projectDonations/ProjectDonations.index.tsx
- src/components/views/project/projectDonations/ProjectTotalFundCard.tsx
- src/context/project.context.tsx
> Move project data to context

- package.json
- src/components/views/donate/SocialBox.tsx
> Hotfix: Social box click

- pages/project/[projectIdSlug]/index.tsx
- src/components/Input.tsx
- src/components/views/project/ProjectIndex.tsx
- src/components/views/projects/ProjectsIndex.tsx
> add infinite scroll to projects

- src/components/views/projects/ProjectsIndex.tsx
> Fix load more issue

- src/components/views/onboarding/DoneStep.tsx
> fix new project button issue on onboarding last step

- src/components/modals/HarvestAll.tsx
> Small typo on GIVbacks Rewards

- lang/en.json
- lang/es.json
- pages/_app.tsx
- src/components/views/create/WalletAddressInput.tsx
> never want the user to enter an exchange address

- src/apollo/gql/gqlPowerBoosting.ts
- src/context/project.context.tsx
> Pass project id to projected rank calculation

- src/components/views/notification/notification.view.tsx
> Recieve notifications when new notification arrives!

- src/components/modals/DonateModal.tsx
- src/components/views/donate/helpers.tsx
> Changing the error message during the transaction Reject

- src/components/notification/NotificationBox.tsx
> Word break issue notification menu

- src/helpers/html.tsx
> support broadcast notification

- src/components/styled-components/Shadow.ts
- src/components/views/homepage/HomeIndex.tsx
- src/components/views/homepage/whyGiveth/DonationCard.tsx
- src/components/views/homepage/whyGiveth/StatsCard.tsx
- src/components/views/homepage/whyGiveth/index.tsx
- src/components/views/project/SimilarProjects.tsx
- src/components/views/projects/ProjectsMainCategories.tsx
> New Homepage - Why Giveth

- src/components/views/project/ProjectTabs.tsx
- src/context/project.context.tsx
> Remove zero allocated boosters

- package.json
- src/components/controller/user.ctrl.tsx
As a requirement made on this [PR](https://github.com/5afe/safe-apps-list/issues/203) we need to auto connect to gnosis safe when we're inside the environment
This PR makes that happen and tries to make a connection, if it fails it keeps the regular flow
It's important so we're listed on Gnosis Safe's app
> Gnosis Safe auto connection

- src/components/views/project/projectDonations/ProjectDonations.index.tsx
> Show project recipient address even if they have not received donation

- src/components/notification/NotificationBox.tsx
> Use server time in notification box

- lang/en.json
- lang/es.json
- src/components/views/project/projectDonations/ProjectTotalFundCard.tsx
> change no donation copy

- src/components/views/homepage/HomeIndex.tsx
- src/components/views/homepage/common.tsx
- src/components/views/homepage/latestUpdates/LatestUpdateCard.tsx
- src/components/views/homepage/latestUpdates/LatestUpdatesBlock.tsx
- src/components/views/homepage/projectUpdatesBlock/ProjectUpdatesBlock.tsx
> 2053 latest updates

- src/components/project-card/ProjectCard.tsx
> added margin to projectcard user name

- src/components/views/homepage/latestUpdates/LatestUpdateCard.tsx
- src/components/views/homepage/latestUpdates/LatestUpdatesBlock.tsx
> Fix latest updates

- lang/en.json
- lang/es.json
- src/content/Partnerships.ts
> remove mycrypto partnership

- src/components/project-card/ProjectCard.tsx
> Change projectcards Author color

- pages/index.tsx
- src/apollo/gql/gqlDonations.ts
- src/apollo/types/types.ts
- src/components/views/homepage/HomeIndex.tsx
- src/components/views/homepage/whyGiveth/DonationCard.tsx
- src/components/views/homepage/whyGiveth/index.tsx
> Homepage integrate recent donations

- src/components/project-card/ProjectCard.tsx
> Donation amounts not matching

- src/components/Header/Header.sc.tsx
- src/components/Header/Header.tsx
> create project button not working on tablet size

- src/components/views/project/ProjectIndex.tsx
> Delete "check out" from the link description

- src/components/views/homepage/whyGiveth/DonationCard.tsx
> add fadein fadeout animation to box-shadow

- src/components/views/homepage/CampaignBlock.tsx
> campaign style fixes

- src/components/views/nft/mint/NFTMintIndex.tsx
> show eligible modal if user is not eligible

- src/components/cards/MintCard.tsx
- src/components/views/nft/mint/NFTMintIndex.tsx
> Add mint page responsiveness

- src/components/styled-components/Tabs.ts
- src/components/views/notification/notification.sc.tsx
- src/components/views/notification/notification.view.tsx
- src/components/views/notification/notificationSettings/SupportedProjects.tsx
- src/components/views/notification/notificationSettings/index.tsx
- src/features/notification/notification.slice.ts
- src/features/notification/notification.types.ts
#2040 [#38](https://github.com/Giveth/notification-center/issues/38)
> add supported project activity notifs

- src/components/views/projects/ProjectsIndex.tsx
> highlight giveth projects responding to turkey crisis

- lang/en.json
- src/components/RewardCard.tsx
- src/components/cards/BaseStakingCard.tsx
- src/components/homeTabs/GIVstream.tsx
- src/components/menu/RewardItems.tsx
- src/components/menu/common.tsx
- src/components/modals/WhatIsStream.tsx
> Fix reward menu

- lang/en.json
- lang/es.json
- src/components/Footer/Footer.tsx
> remove trace link from footer

- src/components/views/homepage/HomeIndex.tsx
- src/components/views/homepage/partners/index.tsx
> Homepage partners
