- src/components/project-card/ProjectCardBadges.tsx
Made totalReactions update on project card badge when props.totalReactions changes
It's a temporary solution for #175. It will not be needed if we solve #177
> Fix homepage totalReactions

- src/components/toasts/index.tsx
Now it looks like this on Mobile devices:
> Fixed Toast size on mobile devices

- src/components/modals/DonateModal.tsx
- src/components/modals/FailedDonation.tsx
- src/components/views/donate/CryptoDonation.tsx
- src/components/views/donate/helpers.tsx
Ref. #880 
I added different donation failed modal for different cases:
1. donations failed
2. donation is mined but not saved on our DB
3. User rejected the transaction!
4. donation cancelled
5. unknown error (is same as failed error)
> Add donation failed messages

- public/images/icons/image.svg
- src/apollo/apolloClient.ts
- src/components/FileUploader.tsx
- src/components/ImageUploader.tsx
- src/components/ProgressBar.tsx
- src/components/modals/EditUserModal.tsx
- src/components/views/create/imageInput/ImageInput.tsx
- src/components/views/onboarding/PhotoStep.tsx
- src/components/views/verification/Common.tsx
- src/components/views/verification/menu/DesktopMenu.tsx
- src/components/views/verification/menu/MobileMenu.tsx
- src/hooks/useUpload.tsx
Ref. #1361 
1. Add progress bar and upload cancel button to file uploading components (create project page, edit user modal and onboarding page)
2. On create project page, when user selects a default background picture (four color slots) or the remove button, all picture uploading processes should be aborted.
> add progress bar to file uploading

- src/components/toasts/InlineToast.tsx
- src/components/views/create/WalletAddressInput.tsx
- src/hooks/useDelay.tsx
Ref. #1185 
1. Fade-in and fade-out animation is added to the resolved address toast massage and to the wallet address already used error message
2. This field is required error message is added when wallet address input is empty
> add animation to multi-addresses

- src/components/cards/BaseStakingCard.sc.tsx
- src/components/cards/BaseStakingCard.tsx
- src/components/homeTabs/GIVfarm.tsx
- src/config/development.ts
- src/config/production.ts
- src/types/config.ts
Sets discontinuation for production farms to stop showing on September 8th as it is exactly 3 weeks after August 18th.
Before that date we'll display them by default and tell the user to remove all liquidity from there
@laurenluz  @divine-comedian we can change the date if you disagree
Test with production env
> Discontinued GIVfarm cards

- src/components/views/donate/ProjectCardSelector.tsx
#1378 
1. User should be able to drag to open/close project card on mobile (current state is on click)
2. When clicking on the blue bar, it returns to project page (but it should close/pull down the project card)
> fix Donate page project card responsiveness issue

- src/apollo/types/types.ts
- src/components/homeTabs/GIVpower.sc.tsx
- src/components/homeTabs/GIVpower.tsx
- src/components/modals/Boost/BoostInnerModal.tsx
- src/components/project-card/ProjectCard.tsx
- src/components/views/project/ProjectTabs.tsx
- src/components/views/project/projectDonateCard/ProjectDonateCard.tsx
- src/components/views/userProfile/ProfileContributes.tsx
- src/features/user/user.queries.ts
fix these issues:
- #1669 
- #1670 
- #1676 
- #1673 
- remove GIVpower on the not verified projects tab from the single project page
- show GIVpower rank in project card only for verified projects.
> Fix testparty issues

- src/components/views/userProfile/UserProfile.view.tsx
This was a last minute UX suggestion from @laurenluz 
If the user holds a Givers NFT in their wallet, is looking at their profile page and has not set a PFP as their profile picture we suggest them to do so and provide a direct link to the setProfilePic Modal. 
If the user does not hold a Givers PFP we show nothing
If the user is viewing any profile, including their own that has a pfp set already as their profile pic then we show a link to view it on Rarible.
> last minute ux improvement

- src/helpers/url.tsx
related to #2635 
This doesn't solve the issue completely but it fixes a minor bug with the formatted string in `removeQueryParam`
> fix: url in removeQueryParam

- src/components/UserWithPFPInCell.tsx
fixes #612 
We should probably update the design for this a bit to make it more obvious that there ae two clickable in that components -> link to the block explorer for that transaction, and the user profile, instead of highlighting the whole component on hover...
> Link to donor profile on project donations tab

- src/components/views/create/AddressInterface.tsx
- src/components/views/create/CreateProject.tsx
- src/components/views/create/CreateProjectAddAddressModal.tsx
- src/components/views/create/WalletAddressInput.tsx
> Update receiving addresses

- src/config/production.ts
this only changes production's BUY_LINK as staging should still link to our fake/test GIV token
> Changes production BUY_LINK to cowswap

- src/components/views/userProfile/projectsTab/ProjectsTable.tsx
> Project Title in my projects should be clickable link

- src/components/menu/RewardItems.tsx
As reported by @divine-comedian the rewards amount would be wrong
I noticed the graph is showing wrong formats as well, maybe because of the pool being inactive for a while now
> HOTFIX:  Rewards count format is wrong for "exploited" pools on mainnet

- .yarnrc.yml
Ensures right version for Giveth, simplifies for new developers that have yarn 2+ as their default version.
> Add .yarnrc.yml to specify which yarn version

- package.json
- sentry.client.config.js
- sentry.edge.config.js
- sentry.server.config.js
Regarding Sentry, according to the [documentation](https://docs.sentry.io/platforms/javascript/configuration/filtering/), we can filter logs using the `beforeSend` hook. I've pushed a hotfix to filter older client logs, and this hotfix extends to filtering edge and server logs as well. Hopefully, this resolves the issue, and we'll only receive urgent errors going forward.
- #3584
> Hotfix set sentry filter for other env

- src/apollo/gql/gqlQF.ts
- src/apollo/types/types.ts
- src/components/views/projects/ProjectsIndex.tsx
- src/components/views/projects/qfBanner/ArchivedQFProjectsBanner.tsx
- src/components/views/projects/qfBanner/common.ts
Related to #3250 
- add sponsors images array and banner image to retrieved graphQL fields
- display images based on the design https://www.figma.com/file/C3HykACu0eNImhAqu0our8/Giveth-projects?type=design&node-id=5897-26523&mode=design&t=VVFxkFuZMTDzkM6A-0
> fix: modify archived QF rounds page UI

- pages/verification/[slug]/index.tsx
removing unnecessary request when fetching projectBySlug in verification form
https://github.com/Giveth/impact-graph/issues/1531
> optimize project verification form

- package.json
- src/components/project-card/ProjectCard.tsx
- src/components/views/archivedQFRounds/ArchivedQFRoundsTable.tsx
- src/components/views/donate/EstimatedMatchingToast.tsx
- src/components/views/project/projectActionCard/QFSection.tsx
- src/helpers/number.ts
- src/helpers/qf.ts
- Format price on format donation for rounded case set to true
- add `getEstimatedMatchingRange` to global QF helpers
- format price for Archived QF table column Matching Pool
> Estimated matching range

- src/components/modals/GIVdropHarvestModal.tsx
- src/hooks/useGivPrice.tsx
- src/hooks/useTokenPrice.tsx
related to https://github.com/Giveth/giveth-dapps-v2/issues/4680
I made these changes 
* As we just get price from gnosis subgraph so I removed `chainId` from `useFetchGIVPrice()` input params.
* When we can't get give price from subgraph we attempt to get the price from coingecko
> Hotfix fix getting giv price on polygon-zkevm chain

- package.json
- pages/_app.tsx
- src/components/modals/SearchModal.tsx
- src/components/project-card/ProjectCard.tsx
- src/components/views/donate/DonateIndex.tsx
- src/components/views/donate/DonatePageProjectDescription.tsx
- src/components/views/donate/OneTime/SelectTokenModal/SelectTokenModal.tsx
- src/components/views/donate/Recurring/SelectTokenModal/SelectTokenModal.tsx
- src/config/production.tsx
- src/services/givpower.ts
- src/services/token.ts
- Giveth/impact-graph#1811
- add USDGLO
- fix styles
- fix unipoolbalance error
cc: @divine-comedian
> Hotfix 2.33.1

- lang/ca.json
- lang/en.json
- lang/es.json
- next-env.d.ts
- src/components/Footer/Footer.tsx
- src/lib/constants/links.ts
https://github.com/Giveth/giveth-dapps-v2/issues/4853
> added footer links to qacc

- src/components/project-card/ProjectCard.tsx
responding to user report of donate button not visible on project card when project is in active qf round 
adjusted height so donate button is clearly visible on mobile view on qf/all or qf eligible projects in active qf round
> HOTFIX: adjust height of project card on mobile qf view
