src/apollo/gql/gqlCampaign.ts, src/apollo/gql/gqlHomePage.ts, src/apollo/gql/gqlProjects.ts, src/apollo/gql/gqlUser.ts, src/apollo/types/types.ts, src/components/project-card/ProjectCard.tsx, src/components/views/homepage/latestUpdates/LatestUpdateCard.tsx
=> Use summary instead of html

src/components/cards/MintCard.tsx
=> Consider NFT balance

lang/en.json, lang/es.json, src/components/InternalLink.tsx
[#2613](https://github.com/Giveth/giveth-dapps-v2/issues/2185)
#2185
=> #2613 Tiny website edits

src/apollo/gql/gqlProjects.ts, src/apollo/gql/gqlVerification.ts, src/apollo/types/types.ts, src/components/views/project/projectDonations/ProjectDonationTable.tsx, src/components/views/project/projectDonations/ProjectTotalFundCard.tsx, src/content/FAQ.tsx, src/lib/constants/links.ts
=> Remove traces of trace

pages/_document.tsx, src/components/controller/general.ctrl.tsx, src/features/general/general.slice.ts, styles/globals.css
=> Faster theme change

src/components/views/nft/mint/NFTMintIndex.tsx
=> 2177 pfp minting page fixes

src/components/views/nft/overview/EligibilityModal.tsx
=> updated learnmore link to documentation

src/components/cards/MintCard.tsx, src/components/views/nft/mint/NFTMintIndex.tsx
=> Update pfp messages

src/components/cards/MintCard.tsx, src/components/views/nft/mint/NFTMintIndex.tsx
=> 2228 check allow list only

src/components/modals/Modal.tsx
=> make overflow auto then overlay

package.json, src/components/modals/Modal.tsx, src/hooks/useModalAnimation.tsx, styles/globals.css
fix: 
- #2246 
- scroll issue on firefox
=> Hotfix 2.7.7

src/components/views/homepage/videoBlock/index.tsx
=> Updated homepage's video

lang/en.json, lang/es.json, package.json, src/components/views/homepage/HomeIndex.tsx, src/components/views/homepage/InformationBlock.tsx, src/components/views/homepage/videoBlock/index.tsx, src/components/views/homepage/whyGiveth/index.tsx, src/components/views/landings/EthDenver/GivethSwag.tsx, src/components/views/landings/EthDenver/givethTalks/CalendarItem.tsx, src/components/views/landings/EthDenver/givethTalks/index.tsx, src/components/views/landings/EthDenver/impactQuest/ImpactDenver.tsx
=> Hotfix 2.8.2

src/components/modals/Boost/BoostedInnerModal.tsx
=> Project Boosted modal has two dismiss button

src/components/views/project/projectDonateCard/ProjectDonateCard.tsx
=> Resume Verification width problem

src/components/toasts/InlineToast.tsx, src/components/views/userProfile/boostedTab/BoostsTable.tsx, src/components/views/userProfile/boostedTab/ProfileBoostedTab.tsx
=> show toast modal for zero GivPower

src/components/menu/NotificationButtonWithMenu.tsx
=> No new notification bug

package.json, src/components/views/landings/EthDenver/givethTalks/index.tsx, src/components/views/landings/EthDenver/impactQuest/ImpactTrackMentorship.tsx
=> Hotfix 2.8.6

src/components/views/project/ProjectUpdates.tsx
=> Text box for project updates keeps expanding when reaching end of line

src/components/menu/UserItems.tsx
=> disconnect wallet on sign out

src/components/Header/Header.sc.tsx, src/components/menu/NotificationButtonWithMenu.tsx
=> fix username overflow

src/components/Grid.tsx, src/components/styled-components/SwiperPagination.tsx, src/components/views/homepage/ProjectsCampaignBlock.tsx, styles/globals.css
=> Changing featured projects style

src/components/Header/Header.tsx, src/components/project-card/ProjectCardLikeAndShareButtons.tsx, src/components/views/project/projectDonateCard/ProjectDonateCard.tsx, src/hooks/useModalCallback.tsx
[#1860](https://github.com/Giveth/giveth-dapps-v2/issues/1860#issuecomment-1455988104)
=> Automate login flow - connect wallet then sign in then do the desired action

src/components/views/projects/ProjectsMainCategories.tsx, src/context/projects.context.tsx
=> move categories handler to context

src/components/views/homepage/latestUpdates/LatestUpdateCard.tsx
=> fix latest updates images

src/components/views/homepage/videoBlock/index.tsx
=> updated video's poster

src/apollo/gql/gqlUser.ts, src/components/modals/AddPolygonAddressModal.tsx, src/lib/helpers.ts
=> Suggest polygon address

src/components/cards/MintCard.tsx, src/components/views/nft/mint/NFTMintIndex.tsx, src/context/pfpmint.context.tsx
=> check eligibility

package.json, src/components/modals/AddPolygonAddressModal.tsx, src/lib/helpers.ts
Reverts Giveth/giveth-dapps-v2#2350
=> Revert "Hotfix adding polygon address modal"

src/components/views/nft/overview/CheckEligibility.tsx, src/components/views/nft/overview/EligibilityModal.tsx, src/components/views/nft/overview/SayHello.tsx
prepare the page ahead of early minting to allow users to check their addresses but not mint
=> remove links to access to minting page

src/components/modals/DonateWrongNetwork.tsx, src/components/modals/SwitchNetwork.tsx
=> Wrong network modal

src/components/views/homepage/whyGiveth/DonationCard.tsx
=> fix recent donations links format

src/components/views/notification/notification.sc.tsx, src/components/views/notification/notificationSettings/common/common.sc.tsx
=> fixed margins

src/components/Input.tsx, src/components/SearchInput.tsx, src/components/views/projects/ProjectsSearchDesktop.tsx, src/components/views/projects/ProjectsSearchTablet.tsx
=> Project input focus

src/components/views/nft/mint/NFTMintIndex.tsx
=> fix pfp success page styles

pages/_app.tsx, src/components/GIVeconomyTab.tsx, src/components/Header/Header.tsx, src/components/modals/WalletModal.tsx, src/lib/helpers.ts
=> Return GIVeconomy tab

lang/en.json
=> Fix switch network i18n problem

src/apollo/gql/gqlDonations.ts, src/apollo/types/types.ts, src/components/views/project/projectDonations/ProjectDonationTable.tsx
[Ref.](https://github.com/Giveth/impact-graph/issues/872)
=> add walletAddress in donation table for users with no name

src/components/views/donate/helpers.tsx
=> Put GIV token order alphabetically

src/components/modals/DonateModal.tsx, src/components/modals/DonateWrongNetwork.tsx, src/components/modals/SwitchNetwork.tsx, src/components/views/create/CreateProject.tsx, src/components/views/create/WalletAddressInput.tsx, src/components/views/donate/CryptoDonation.tsx, src/components/views/verification/manageFunds/AddAddressModal.tsx
=> Comment optimism functionality

src/components/views/donate/CryptoDonation.tsx, src/helpers/blockchain.ts
=> Fix xdai balance

src/lib/constants/regex.ts
=> fix adding youtube links

package.json, src/components/RichTextInput.tsx, src/components/richImageUploader/imageUploader.js, styles/globals.css, yarn.lock
=> Fix pasting image to quill editor

src/components/modals/HarvestAll.tsx
=> fix harvest usd price

src/components/Header/Header.tsx, src/components/menu/GIVeconomyItems.tsx, src/components/menu/LinkWithMenu.tsx, src/components/menu/menuRoutes.ts, src/content/FAQ.tsx, src/lib/constants/Routes.ts, src/lib/constants/Tabs.ts
=> Add home menu clickable

src/components/Header/HeaderWrapper.tsx
=> Show loading until menu appears

src/components/modals/UploadProfilePicModal/NFTButtons.tsx, src/components/modals/UploadProfilePicModal/OnboardButtons.tsx, src/components/setProfilePic/SetProfilePic.tsx, src/hooks/useAvatar.ts
=> Fix upload profile loading

src/helpers/blockchain.ts
update based on: https://docs.gnosischain.com/developers/interact/metamask
=> update gnosis chain params

pages/test1.tsx, src/components/modals/HarvestAll.tsx, src/hooks/useStakingPool.tsx
=> Fix harvest modal

src/components/GIVeconomyPages/GIVstream.tsx, src/components/modals/ConfirmSubmit.tsx, src/components/modals/StakeLock/StakeGIV.tsx, src/components/toasts/claim.tsx, src/components/views/nft/mint/NFTMintIndex.tsx, src/helpers/blockchain.ts, src/lib/helpers.ts, src/lib/notifications/claim.tsx, src/lib/notifications/drop.tsx, src/lib/notifications/harvest.tsx, src/lib/notifications/stake.tsx, src/lib/notifications/withdraw.tsx
=> Fix switch networks

src/components/views/nft/mint/NFTMintIndex.tsx
=> Update redirect on success view

src/components/PFP.tsx, src/components/views/userProfile/UserProfile.view.tsx
=> Add cosmetic to profile view

lang/ca.json, lang/en.json, lang/es.json
=> Copy fix - Projects page "All projects" banner

lang/ca.json, lang/en.json, lang/es.json, src/config/development.ts, src/config/production.ts
=> Add archived label to FOX farm & change archive label copy

src/apollo/gql/gqlProjects.ts, src/components/project-card/ProjectCardAlt.tsx
=> add PFP to Project alt card

src/components/PFP.tsx
=> moved tooltip to right

lang/ca.json, lang/en.json, lang/es.json, package.json, src/components/SocialBox.tsx, src/components/modals/ShareModal.tsx, src/components/project-card/ProjectCardLikeAndShareButtons.tsx, src/components/views/create/SuccessfulCreation.tsx, src/components/views/donate/DonateIndex.tsx, src/components/views/donate/ProjectCardSelector.tsx, src/components/views/donate/SuccessView.tsx, src/components/views/project/projectDonateCard/ProjectDonateCard.tsx, src/lib/constants/shareContent.ts, yarn.lock
=> changing draft share content

src/components/PFP.tsx, src/components/UserWithPFPInCell.tsx, src/components/project-card/ProjectCardUserName.tsx, src/components/views/project/ProjectOwnerWithPfp.tsx, src/components/views/project/projectDonations/ProjectDonationTable.tsx
small fixes in the vertical alignment of the donation table
and also the display of the PFPs in the table cells
=> small fixes from pfp integration

src/components/views/project/ProjectHeader.tsx, src/components/views/project/ProjectIndex.tsx, yarn.lock
=> added new project banner styles

lang/ca.json, lang/en.json, lang/es.json, src/components/views/project/SimilarProjects.tsx
=> single project view - Similar projects

src/components/views/project/ProjectBadge.tsx, src/components/views/project/ProjectBadges.tsx, src/components/views/project/ProjectIndex.tsx
=> New project badges

lang/ca.json, lang/en.json, lang/es.json, package.json, src/components/PFP.tsx, src/components/views/project/ProjectIndex.tsx, src/components/views/project/projectActionCard/DonationSection.tsx, src/components/views/project/projectActionCard/LikeAndShareSection.tsx, src/components/views/project/projectActionCard/ProjectActionCard.tsx, yarn.lock
=> Add new donate card

src/components/views/donate/CryptoDonation.tsx, src/components/views/donate/helpers.tsx
Following this [discussion](https://github.com/Giveth/giveth-dapps-v2/issues/2598#event-9149003106)
=> Sends network main token to top of the list

src/components/views/donate/CryptoDonation.tsx, src/components/views/donate/helpers.tsx
Reverts Giveth/giveth-dapps-v2#2607
=> Revert "Sends network main token to top of the list"

src/components/views/project/ProjectHeader.tsx, src/components/views/project/ProjectIndex.tsx, src/components/views/project/ProjectTabs.tsx
=> New project tabs

src/components/project-card/ProjectCard.tsx, src/components/project-card/ProjectCardUserName.tsx
https://github.com/Giveth/giveth-dapps-v2/issues/2565#issuecomment-1537364147
=> Fix author color

src/components/views/project/ProjectIndex.tsx, src/components/views/project/ProjectTimeline.tsx, src/components/views/project/ProjectUpdates.tsx, src/components/views/project/projectUpdates/common.styled.tsx
=> public view updates list

src/components/views/project/ProjectUpdates.tsx
=> Disable Submit Update Button after submitting

lang/ca.json, lang/en.json, lang/es.json, src/components/views/project/projectGIVPower/GIVPowerGetReward.tsx
=> Added givbackFactor

src/components/views/project/projectGIVPower/GIVPowerGetReward.tsx
=> fixed percentage decimals

lang/en.json, src/components/modals/Boost/BoostedInnerModal.tsx
=> Boosted modal copy

lang/ca.json, lang/en.json, lang/es.json, src/apollo/types/types.ts, src/components/menu/FilterMenu.tsx, src/helpers/url.tsx
=> Add filter on chains

src/content/metatags.ts
=> Change copy of Giveth project link metadata

src/components/menu/Menu.sc.tsx, src/components/menu/NotificationButtonWithMenu.tsx, src/components/menu/NotificationItems.tsx
=> Fix notification link issue

src/components/views/projects/ProjectsSortSelect.tsx, src/context/projects.context.tsx
=> Add givpower sort

package.json, src/components/modals/SearchModal.tsx, src/components/views/projects/ProjectsSortSelect.tsx
=> Hotfix 2.15.7

lang/ca.json, lang/en.json, lang/es.json, package.json, src/components/menu/FilterMenu.tsx, src/components/views/project/projectGIVPower/GIVPowerGetReward.tsx, src/components/views/project/projectGIVPower/NoBoost.tsx, src/components/views/project/projectGIVPower/index.tsx, src/components/views/projects/ProjectsSortSelect.tsx
=> Hotfix 2.15.8

lang/ca.json, lang/en.json, lang/es.json, src/components/views/project/projectDonations/ProjectDonations.index.tsx, src/components/views/project/projectDonations/ProjectTotalFundCard.tsx, src/components/views/project/projectDonations/ProjectWalletAddress.tsx
=> Update donate card

src/config/development.ts, src/config/production.ts
~~Not sure if this is the correct change. We technically have no staging environment deployed on studio. Reusing the production gnosischain one in `development.ts`.
`production.ts`should be good with the changes made.~~
I added a staging deployment.
=> Changing thegraph from "hosted service" to "graph studio"

src/components/menu/ProjectsItems.tsx
[2651](https://github.com/Giveth/giveth-dapps-v2/issues/2651#issuecomment-1565899666)
=> Fix projects route

src/components/GIVeconomyPages/GIVbacks.tsx, src/components/views/project/projectGIVPower/GIVpowerCard.tsx
=> Add update date to GIVpower card

pages/qf/[slug].tsx, src/components/views/projects/QFProjectsBanner.tsx
=> Update qf projects page

src/components/styled-components/SwiperPagination.tsx, src/components/views/homepage/HomeIndex.tsx, src/components/views/homepage/ProjectsCampaignBlock.tsx, src/components/views/project/SimilarProjects.tsx
=> update similar projects

src/components/views/project/projectActionCard/ProjectActionCard.tsx, src/components/views/project/projectActionCard/QFSection.tsx
=> Qf project action card

src/lib/subgraph/subgraphQueryBuilder.ts, src/services/subgraph.service.ts
=> Fix query builder

src/apollo/gql/gqlProjects.ts, src/apollo/types/types.ts, src/components/project-card/ProjectCard.tsx, src/components/views/project/projectActionCard/ProjectActionCard.tsx, src/components/views/project/projectActionCard/QFSection.tsx, src/helpers/qf.ts
=> Connect qf backend

src/components/views/userProfile/donationsTab/DonationsTable.tsx
=> Fix donation table hover

src/apollo/types/types.ts, src/components/project-card/ProjectCard.tsx, src/components/project-card/ProjectCardOrgBadge.tsx
=> Update project card

src/components/views/project/projectActionCard/DonationSection.tsx, src/components/views/project/projectActionCard/QFSection.tsx
=> Update action card

src/components/views/project/projectActionCard/ProjectPublicActions.tsx, src/components/views/project/projectActionCard/QFSection.tsx, src/helpers/qf.ts
=> Add qf formulas

src/components/NetworkSelector.tsx, src/lib/constants/selectCustomStyles.ts
=> New network selector

src/config/development.ts, src/config/production.ts
=> Moving config to env file

src/apollo/gql/gqlDonations.ts, src/components/views/project/projectDonations/ProjectDonations.index.tsx
=> Connect donation tab to backend

src/components/views/donate/CryptoDonation.tsx, src/components/views/donate/EstimatedMatchingToast.tsx
=> Add estimatedmatching donation

src/components/views/project/projectDonations/ProjectDonationTable.tsx, src/components/views/project/projectDonations/ProjectDonations.index.tsx, src/components/views/project/projectDonations/ProjectTotalFundCard.tsx
=> Fix donation table for QF

package.json, src/config/production.ts
These should not be hard coded in here as we are now exposing our API key. However - the key is limited from thegraph dashboard
=> Use subgraph studio endpoints on production frontend

src/components/views/project/ProjectBadges.tsx, src/components/views/project/ProjectHeader.tsx, src/components/views/project/projectActionCard/ProjectActionCard.tsx, src/components/views/project/projectActionCard/QFSection.tsx
=> Fix qf styles

src/components/views/donate/QFToast.tsx
https://github.com/Giveth/giveth-dapps-v2/issues/2693#issuecomment-1605885623
=> fix passport link

src/components/views/donate/QFToast.tsx
https://github.com/Giveth/giveth-dapps-v2/issues/2693#issuecomment-1608124977
=> fix go to passport link to internal link

src/components/views/donate/SuccessView.tsx, src/context/donate.context.tsx
https://github.com/Giveth/giveth-dapps-v2/issues/2693#issuecomment-1608765851
=> Switch to donate view if user is changed

src/components/views/userProfile/ProfileOverviewTab.tsx
=> fix-passport-card-link-on-my-account

pages/qf/index.tsx, src/components/menu/FilterMenu.tsx, src/context/projects.context.tsx
=> Add verified to qf query

src/apollo/gql/gqlProjects.ts, src/components/views/donate/CryptoDonation.tsx, src/components/views/donate/SuccessView.tsx, src/context/donate.context.tsx
=> Compare QF rounds begin date with user time

src/components/views/project/projectActionCard/QFSection.tsx
=> Project single responsive

pages/qf/index.tsx, src/components/menu/FilterMenu.tsx, src/context/projects.context.tsx
=> Revert verified query for qf

lang/ca.json, lang/en.json, lang/es.json, src/components/views/project/projectDonations/ProjectTotalFundCard.tsx, src/components/views/projects/QFProjectsBanner.tsx
=> fix qf banner title for not active round

src/apollo/gql/gqlProjects.ts, src/helpers/qf.ts
=> Change activeround condition

src/components/views/project/SimilarProjects.tsx
=> fix similar projects

src/components/views/project/projectActionCard/DonationSection.tsx
=> use countUniqueDonors

src/components/UserWithPFPInCell.tsx
=> check user exists

src/components/project-card/ProjectCard.tsx, src/components/views/project/projectActionCard/DonationSection.tsx, src/components/views/project/projectActionCard/QFSection.tsx, src/components/views/project/projectDonations/ProjectTotalFundCard.tsx, src/helpers/number.ts
=> Show very few donations

src/components/project-card/ProjectCardUserName.tsx
=> Created UserNameContainer

lang/ca.json, lang/en.json, lang/es.json
=> Update "Other" project type description

src/components/views/project/ProjectGIVbackToast.tsx
=> add handle open query

lang/ca.json, lang/en.json, lang/es.json, src/components/modals/SwitchNetwork.tsx, src/components/views/donate/SaveGasFees.tsx, src/components/views/donate/common.styled.ts
=> Show switch network for save gas

src/helpers/qf.ts
https://github.com/Giveth/giveth-dapps-v2/issues/2886#issuecomment-1634650868
=> Updated QF estimate matching 

src/helpers/number.ts, src/helpers/qf.ts
=> Fix calculate total estimated matching

lang/en.json, src/components/project-card/ProjectCard.tsx, src/components/views/project/projectActionCard/DonationSection.tsx, src/components/views/project/projectDonations/ProjectTotalFundCard.tsx
fixes #2824 
fixes #2899
fixes #2840
=> fix(copy): project-page

lang/ca.json, lang/en.json, lang/es.json, src/components/Dropdown.tsx, src/components/badges/ShareLikeBadge.tsx, src/components/project-card/ProjectCard.tsx, src/components/views/GIVferral.view.tsx, src/components/views/project/ProjectIndex.tsx, src/components/views/project/projectActionCard/AdminActions.tsx, src/components/views/project/projectActionCard/DonationSection.tsx, src/components/views/project/projectActionCard/ProjectActionCard.tsx, src/components/views/project/projectActionCard/ProjectPublicActions.tsx, src/components/views/project/projectActionCard/ProjectStats.tsx
=> Add owner action card

src/components/views/project/projectActionCard/DonationSection.tsx, src/helpers/number.ts
=> Fix format donations for rounded

src/components/views/homepage/introBlock/index.tsx
=> fix our mission link hover color

src/components/project-card/ProjectCard.tsx
=> Show qf label for non verified projects

lang/ca.json, lang/en.json, lang/es.json, src/components/views/projects/ProjectsSortSelect.tsx
=> Change sort copy

src/components/views/project/ProjectGIVbackToast.tsx
=> round givback factor

src/components/menu/ProjectsItems.tsx, src/components/views/donate/QFToast.tsx, src/lib/constants/Routes.ts
=> "Go to Projects" instead of passport for eligible QF donors

lang/en.json, src/components/Dropdown.tsx, src/components/VerificationBadge.tsx, src/components/badges/VerifiedBadge.tsx, src/components/project-card/ProjectCardAlt.tsx, src/components/views/project/projectActionCard/AdminActions.tsx, src/components/views/project/projectActionCard/ProjectStats.tsx, src/components/views/project/projectActionCard/QFSection.tsx, src/components/views/userProfile/projectsTab/ProjectsTable.tsx
=> Owener view bug fixes

src/components/views/project/ProjectBadges.tsx
=> fixed badges texts

src/components/project-card/ProjectCard.tsx, src/lib/helpers.ts
=> project last updated problem

src/components/views/donate/helpers.tsx, src/lib/helpers.ts
=> fix donationId zero problem

src/components/PassportBanner.tsx, src/features/user/user.slice.ts, src/hooks/usePassport.ts
=> Fix passport

src/components/views/donate/DonateIndex.tsx, src/context/donate.context.tsx
=> Remove qb banner for non qf donation page

pages/index.tsx, pages/qf/index.tsx, src/apollo/gql/gqlOptions.ts, src/components/views/projects/ProjectsSortSelect.tsx, src/context/projects.context.tsx
=> Return instant boosting

pages/projects/[slug].tsx, pages/projects/index.tsx, pages/qf/[slug].tsx, pages/qf/index.tsx, src/components/menu/FilterMenu.tsx, src/components/views/projects/ProjectsFiltersButton.tsx, src/context/projects.context.tsx
=> Add qf filter to projects page

src/components/Dropdown.tsx, src/components/views/projects/ProjectsFiltersButton.tsx, src/hooks/useOnClickOutside.tsx
=> add active ability to useOnClickOutside

src/components/views/project/projectDonations/ProjectDonationTable.tsx
=> make usd amount default sort

src/components/PassportBanner.tsx
=> Fix passport banner responsive

src/components/views/create/CreateProjectAddAddressModal.tsx, src/components/views/create/WalletAddressInput.tsx
=> Fix create project input

src/components/modals/ManageProjectAddresses/ManageProjectAddressesModal.tsx, src/components/modals/SwitchNetwork.tsx, src/components/views/donate/TokenPicker.tsx, src/components/views/verification/manageFunds/AddAddressModal.tsx
=> Fix app to auto fetch networks

src/components/Header/Header.sc.tsx, src/components/Header/Header.tsx
=> Fixing create a project button on header in the single project page

src/components/views/create/AddressInterface.tsx, src/components/views/create/CreateProject.tsx, src/components/views/create/CreateProjectAddAddressModal.tsx, src/components/views/create/WalletAddressInput.tsx
=> Updated input functionality for recipient addresses

src/components/views/project/projectDonations/ProjectDonationTable.tsx, src/lib/helpers.ts
=> Amount column should be wider

src/components/Badge.tsx, src/components/VerificationBadge.tsx, src/components/views/project/projectActionCard/ProjectStats.tsx
=> Verification badge overflowing

src/components/RichTextInput.tsx, src/components/RichTextViewer.tsx, src/components/styled-components/Quill.ts, src/components/views/project/projectUpdates/UpdatesSection.tsx
=> Text is overlapping on the updates page

src/components/views/donate/CryptoDonation.tsx, src/context/projects.context.tsx
Reverts Giveth/giveth-dapps-v2#3012
@MoeNick based on our call.
=> Revert "Add set max token amount on donation input"

src/components/views/donate/CryptoDonation.tsx, src/components/views/donate/InputBox.tsx
=> Add max amount

src/components/menu/CommunityItems.tsx, src/components/views/about/AboutIndex.tsx, src/components/views/homepage/introBlock/index.tsx
=> Updated mission links

src/components/ContributeCard.tsx, src/context/project.context.tsx, src/services/givpower.ts
=> Fix givpower tab amounts

src/components/views/project/ProjectIndex.tsx, src/components/views/project/projectActionCard/MobileDonateFooter.tsx, src/components/views/project/projectActionCard/ProjectActionCard.tsx, src/components/views/project/projectActionCard/ProjectPublicActions.tsx
=> Project page new footer

lang/ca.json, lang/en.json, lang/es.json
=> Capitalization of headings

src/components/views/userProfile/projectsTab/ProjectsTable.tsx
=> remove link for cancelled projects

src/components/modals/WalletModal.tsx, src/lib/wallet/walletTypes.ts
=> Updated Metamask Title and Subtitle

pages/account.tsx, pages/user/[address].tsx, src/apollo/gql/gqlPowerBoosting.ts, src/components/ContributeCard.tsx, src/components/views/userProfile/ProfileContributes.tsx, src/components/views/userProfile/ProfileLikedTab.tsx, src/components/views/userProfile/ProfileOverviewTab.tsx, src/components/views/userProfile/UserProfile.view.tsx, src/components/views/userProfile/boostedTab/BoostsTable.tsx, src/components/views/userProfile/boostedTab/ProfileBoostedTab.tsx, src/components/views/userProfile/boostedTab/PublicBoostsTable.tsx, src/components/views/userProfile/boostedTab/PublicProfileBoostedTab.tsx, src/components/views/userProfile/boostedTab/useFetchPowerBoostingInfo.ts, src/components/views/userProfile/donationsTab/ProfileDonationsTab.tsx, src/components/views/userProfile/projectsTab/ProfileProjectsTab.tsx, src/context/profile.context.tsx, src/helpers/givpower.ts, yarn.lock
=> Fix boost table for public profile

src/components/views/project/projectDonations/ProjectTotalFundCard.tsx
=> rounded estimated matching

lang/ca.json, lang/en.json, lang/es.json, src/components/views/create/CreateProject.tsx, src/components/views/create/NameInput.tsx, src/lib/helpers.ts
=> At least one wallet address should be required

src/components/views/project/projectDonations/ProjectDonationTable.tsx, src/components/views/userProfile/donationsTab/DonationsTable.tsx, src/lib/helpers.ts
=> Improving showing amount and usd value in donation table

src/components/ArchiveAndNetworkCover/WrongNetworkCover.tsx, src/components/Header/Header.tsx, src/components/PassportButton.tsx, src/components/controller/general.ctrl.tsx, src/components/controller/modal.ctrl.tsx, src/components/controller/notification.ctrl.tsx, src/components/controller/price.ctrl.tsx, src/components/controller/subgraph.ctrl.tsx, src/components/controller/user.ctrl.tsx, src/components/menu/UserButtonWithMenu.tsx, src/components/menu/UserItems.tsx, src/components/modals/EditUserModal.tsx, src/components/modals/SignWithWalletModal.tsx, src/components/modals/WelcomeModal.tsx, src/features/user/user.thunks.ts, src/features/user/user.types.ts, src/hooks/useAvatar.ts, src/hooks/usePassport.ts, src/services/passport.ts
=> Update user and header to wagmi

src/config/development.tsx, src/config/production.tsx
=> Add op giv buy link

src/components/cards/StakingCards/BaseStakingCard/StakingPoolInfoAndActions.tsx, src/components/views/givfarm/GIVfarmTop.tsx, src/context/farm.context.tsx, src/lib/subgraph/subgraphQueryBuilder.ts
=> Fix reward on givfarm

src/components/NetworkSelector.tsx, src/lib/subgraph/subgraphDataHelper.ts, src/services/subgraph.service.ts
=> Fix giveconomy issues

package.json, src/lib/subgraph/subgraphQueryBuilder.ts
=> Fixed graphql query builder when no givpower is defined

src/components/views/userProfile/boostedTab/BoostsTable.tsx
=> showing the "GIVpower Amount"

src/components/views/create/NameInput.tsx
=> fix character counter

src/components/BlogCard.tsx
=> make the title clickable in recent posts

package.json, src/components/views/donate/CryptoDonation.tsx
=> Fix showing user balance

src/context/project.context.tsx
https://github.com/Giveth/giveth-dapps-v2/issues/3058#issuecomment-1705494538
=> remove backend error toast from project view

src/components/views/userProfile/projectsTab/ProjectsTable.tsx
=> formatting for really long project names on My Projects table

src/components/views/project/projectDonations/ProjectDonations.index.tsx
=> Problem in displaying project's donation tab on STG

src/components/views/create/CreateProject.tsx
=> Adding Cancel button in creation project page

pages/landings/givbacks.tsx, src/components/styled-components/Bullets.ts, src/components/views/landings/GIVBacks/GIVBacksHeader.tsx, src/components/views/landings/GIVBacks/GiveAndGetGIVback.tsx, src/components/views/landings/GIVBacks/HowGIVbacksWork.tsx, src/components/views/landings/GIVBacks/JoinTheRevolution.tsx, src/components/views/landings/GIVBacks/OfTheDonors.tsx, src/components/views/landings/GIVBacks/WhatAreGIVbacks.tsx, src/components/views/landings/GIVBacks/WhatCanYouDo.tsx, src/components/views/landings/GIVBacks/WhatMakesGIVbacks.tsx, src/components/views/landings/GIVBacks/YouKnowHow.tsx, src/components/views/landings/GIVBacks/index.tsx
=> Landing page for learn how givbacks works

src/components/modals/EditUserModal.tsx
=> remove delete pic button when no pic

src/components/views/homepage/whyGiveth/StatsCard.tsx, src/components/views/homepage/whyGiveth/index.tsx
=> Remove horizontal scroll

src/components/views/project/projectDonations/ProjectDonations.index.tsx, src/components/views/project/projectDonations/QfRoundSelector.tsx
Related to https://github.com/Giveth/giveth-dapps-v2/issues/2915
=> add toggles for selecting qf round

src/components/views/project/ProjectIndex.tsx, src/components/views/project/ProjectOwnerBanner.tsx, src/components/views/project/projectActionCard/AdminActions.tsx, src/components/views/project/projectActionCard/ProjectActionCard.tsx
=> Project owner view

src/components/views/project/projectActionCard/AdminActions.tsx
=> fixed project admin's active options on mobile

src/components/views/project/ProjectIndex.tsx
=> Fixed draft conditions on mobile

src/apollo/gql/gqlProjects.ts, src/apollo/types/types.ts, src/components/views/project/ProjectBadges.tsx
=> Campaign badges

src/components/views/project/projectGIVPower/index.tsx, src/context/project.context.tsx
=> Fix nan on givpower table

src/components/AmountInput.tsx
=> use toFixed in converting to bigint

src/components/modals/StakeLock/LockInfo.tsx
=> fix lock info calculation

src/components/AmountInput.tsx, src/components/GIVeconomyPages/GIVbacks.tsx, src/components/modals/GIVdropHarvestModal.tsx, src/components/modals/StakeLock/StakeGIV.tsx, src/components/views/claim/cards/Donate.tsx, src/components/views/claim/cards/Govern.tsx, src/components/views/claim/cards/Stake.tsx, src/components/views/donate/CryptoDonation.tsx, src/lib/contractHelper/UnipoolHelper.ts
=> Double check bigint conversion

src/components/views/donate/CryptoDonation.tsx
=> Fixed donation balance issue

src/components/views/donate/CryptoDonation.tsx
=> Fixed connect-wallet on donation

src/components/views/projects/ProjectsSearchTablet.tsx
=> removed project search focus

src/components/modals/StakeLock/Lock.tsx
=> fix lock button disable condition

src/components/views/projects/ProjectsBanner.tsx, src/components/views/projects/ProjectsIndex.tsx
=> Remove unnecessary gap on mobile

src/components/views/userProfile/boostedTab/PublicBoostsTable.tsx
=> remove dollar sign

src/components/FloatingReferral.tsx
=> added FloatingReferral responsive

src/components/SocialBox.tsx, src/components/modals/ShareModal.tsx
=> Fix twitter issues

src/components/project-card/ProjectCardLikeAndShareButtons.tsx
=> Show boost modal directly

src/components/views/project/ProjectBadges.tsx
=> fix Badges Spacing

lang/ca.json, lang/en.json, lang/es.json, src/components/NotAvailableProject.tsx, src/components/views/EditIndex.tsx
https://github.com/Giveth/giveth-dapps-v2/issues/3068#issuecomment-1706895059
=> Only the project owner can edit this project

package.json, src/components/views/donate/CryptoDonation.tsx
=> fix calcMaxDonation

src/components/NotAvailableProject.tsx, src/components/views/EditIndex.tsx, src/components/views/project/ProjectIndex.tsx
=> Fix draft projects

pages/user/[address].tsx
=> set myAccount true if the wallet address and singed user are same

src/apollo/gql/gqlQF.ts, src/components/Header/Header.tsx, src/components/menu/ProjectsItems.tsx, src/components/views/projects/ProjectsMainCategories.tsx, src/features/general/general.slice.ts, src/features/general/general.thunk.ts
=> Remove qf link if there is no active round

src/components/views/project/projectDonations/ProjectTotalFundCard.tsx
=> changed notDistributedFund condition

src/components/views/donate/CryptoDonation.tsx, src/components/views/donate/SuccessView.tsx, src/components/views/project/projectActionCard/ProjectEligibleQFChains.tsx, src/components/views/project/projectActionCard/QFSection.tsx
=> Specific chain qf fixes

src/components/views/project/projectDonations/ProjectDonations.index.tsx
=> fix NoDonation condition

package.json, src/components/NotAvailableProject.tsx, src/components/views/project/ProjectIndex.tsx, src/components/views/project/projectActionCard/ProjectStats.tsx, src/context/project.context.tsx, yarn.lock
=> Fix not available

src/components/views/project/projectDonations/ProjectTotalFundCard.tsx
=> Added QF tx-link

pages/qf/index.tsx, src/apollo/types/gqlEnums.ts, src/context/projects.context.tsx
=> Qf sorting

src/components/views/project/ProjectBadges.tsx
=> fixed campaign scroll issue

lang/ca.json, lang/en.json, lang/es.json, src/components/views/donate/DonateIndex.tsx, src/components/views/project/projectActionCard/ProjectPublicActions.tsx, src/components/views/project/projectDonations/NoDonation.tsx, src/components/views/project/projectDonations/ProjectDonationTable.tsx, src/components/views/project/projectDonations/ProjectDonations.index.tsx
=> Udpate copies

src/components/NetworkSelector.tsx, src/config/development.tsx
=> Change network and sign in with etc

next.config.js, pages/_app.tsx, src/components/modals/LanguageModal.tsx, src/lib/helpers.ts, src/lib/localStorage.ts, src/tests/utils.tsx
=> Change language based on browser settings

pages/projects/[slug].tsx, pages/qf/[slug].tsx, src/components/views/projects/ProjectsSortSelect.tsx
=> Fix sort options

src/apollo/types/types.ts, src/components/menu/FilterMenu.tsx
=> Add filter AcceptFunds on ETC

src/components/views/project/ProjectGIVbackToast.tsx, src/components/views/project/projectActionCard/AdminActions.tsx
Reverts Giveth/giveth-dapps-v2#3368
=> Revert "Add verify button to inline toast"

package.json, src/components/views/homepage/GitcoinGrantsBanner.tsx, src/components/views/homepage/TorusBanner.tsx
=> Fix homepage banner positioning

src/components/views/project/ProjectGIVbackToast.tsx, src/components/views/project/projectActionCard/AdminActions.tsx, src/context/project.context.tsx
Add conditional verification buttons:
https://www.figma.com/file/C3HykACu0eNImhAqu0our8/Giveth-projects?node-id=4896%3A11910&mode=dev
=> Add conditional verification buttons

src/features/subgraph/subgraph.thunks.ts, src/hooks/useStakingPool.ts
=> Fix other network cards info

package.json, src/components/views/homepage/TorusBanner.tsx
=> Fix torus banner position after removing Gitcoin banner

src/context/projects.context.tsx
=> fix QF page's default sort

src/helpers/qf.ts, src/lib/constants/constants.ts
=> Change QF matching cap

src/solana/solanaWalletProvider.tsx
Made Solana Burner wallet only enable for test env
Added Solana Solflare Wallet
#3400
=> Solana Support Patch

lang/en.json, src/apollo/gql/gqlUser.ts, src/components/Badge.tsx, src/components/VerificationBadge.tsx
=> Fix badge colors and user projects badges and rejected copy

src/components/views/verification/projectContact/ProjectContactIndex.tsx, src/lib/constants/regex.ts
=> fix regex for linkedin urls

src/components/views/donate/CryptoDonation.tsx, src/components/views/donate/DonateQFEligibleNetworks.tsx, src/components/views/donate/QFModal.tsx
=> Fix showing QF matching modal

package.json, src/apollo/gql/gqlProjects.ts, src/apollo/types/gqlTypes.ts, src/components/modals/DonateModal.tsx, src/components/views/donate/EstimatedMatchingToast.tsx, src/hooks/useTokenPrice.tsx
=> Fix estimated matching of 0

src/components/controller/modal.ctrl.tsx, src/components/controller/notification.ctrl.tsx, src/components/modals/EditUserModal.tsx, src/components/modals/SignWithWalletModal.tsx, src/components/setProfilePic/SetProfilePic.tsx, src/components/views/onboarding/InfoStep.tsx, src/hooks/useAvatar.ts, src/hooks/usePurpleList.ts
Fixed some issues with solana user
Ref #3400
=> Solana Authentication Hotfix 

src/apollo/types/types.ts, src/artifacts/createProfile.json, src/config/development.tsx, src/config/production.tsx, src/hooks/useCreateAnchorContract.ts, src/types/config.ts
#3440 
This PR introduces the hook we'll use for creating the anchor contract. I implemented it separately to ensure that @MohammadPCh can also utilize it in his branch.
=> Create anchor contract hook

pages/_app.tsx, src/components/menu/GIVeconomyItems.tsx, src/components/menu/NotificationButtonWithMenu.tsx, src/features/subgraph/subgraph.services.ts, src/lib/stakingPool.ts
=> Fix errors

src/services/donation.ts
=> recurring create donations

package.json, pages/test2.tsx, src/components/modals/FailedDonation.tsx
=> Update fail donation modal

src/components/views/create/CreateProject.tsx, src/components/views/create/DescriptionInput.tsx
=> fix scrolling to description error

src/hooks/useTokenPrice.tsx
Fixed issue in fetching solana price
=> Hotfix SOL Price

pages/api/donation-backup.js, src/hooks/useCreateDonation.tsx
=> Add donation backup

lang/ca.json, lang/en.json, lang/es.json, pages/projects/[slug].tsx, pages/qf/[slug].tsx, src/apollo/gql/gqlProjects.ts, src/components/menu/ProjectsItems.tsx, src/components/views/projects/ProjectsFiltersSwiper.tsx, src/components/views/projects/ProjectsIndex.tsx, src/components/views/projects/ProjectsMainCategories.tsx
=> Add new categories to giveth for polygon qf round

lang/ca.json, lang/en.json, lang/es.json
=> change polygon category desc

src/lib/constants/constants.ts
=> change cap to 4 percent

pages/_app.tsx, scripts/generate-robots-txt.js, src/components/cards/MintCard.tsx, src/components/menu/FilterMenu.tsx, src/components/modals/ManageProjectAddresses/AddNewAddress.tsx, src/components/modals/ShareRewardedModal.tsx, src/components/rich-text/RichTextInput.tsx, src/components/setProfilePic/SetProfilePic.tsx, src/components/views/donate/DonateModal.tsx, src/components/views/donate/SelectTokenModal/SelectTokenModal.tsx, src/components/views/project/projectDonations/ProjectDonationTable.tsx, src/components/views/userProfile/projectsTab/ProjectItem.tsx, src/components/views/userProfile/projectsTab/ProjectQFStatus.tsx, src/config/production.tsx, src/configuration.ts, src/context/claim.context.tsx, src/features/user/user.thunks.ts, src/lib/constants/links.ts, src/lib/helpers.ts, src/lib/stakingPool.ts, src/services/donation.ts, src/services/passport.ts, src/services/token.ts
remove extra console logs to optimize performance https://github.com/Giveth/devops/issues/195
=> remove extra console logs

src/components/views/donate/SuccessView.tsx
[https://github.com/Giveth/devops/issues/194](https://github.com/Giveth/devops/issues/194)
=> Remove Confetti from Donation Success Page

src/lib/helpers.ts
=> fix address suggestion

src/components/views/donate/TotalDonation.tsx
https://github.com/Giveth/giveth-dapps-v2/issues/3488#issuecomment-1890943704
=> format total donation Price

src/components/views/donate/DonateIndex.tsx, src/components/views/donate/DonationInfo.tsx
=> It says donation submitted, but i haven't done any donations yet

src/components/menu/UserItems.tsx
=> fixed user menu switch network fn on Solana

src/providers/generalWalletProvider.tsx
=> fixed phantom switch wallet issue.

src/providers/generalWalletProvider.tsx
=> fixed scroll issue on solana

src/components/cards/MintCard.tsx, src/components/menu/UserItems.tsx, src/components/modals/WrongNetworkInnerModal.tsx, src/providers/generalWalletProvider.tsx
=> Solana giveconomy

package.json, pages/test1.tsx, src/components/rich-text/RichTextCounter.tsx, src/components/rich-text/RichTextInput.tsx, src/components/views/create/DescriptionInput.tsx, src/components/views/project/projectUpdates/UpdatesSection.tsx, src/components/views/project/projectUpdates/index.tsx
=> fix Minimum Character Count for Project Descriptions

pages/api/donation-backup.js
=> add timestamp

src/components/modals/SignWithWalletModal.tsx
=> added loading to solana signin

src/components/NetworkLogo.tsx, src/lib/network.ts
[#3394](https://github.com/Giveth/giveth-dapps-v2/issues/3394#issuecomment-1898502259)
=> fix solana logo and chain name

src/components/views/donate/CryptoDonation.tsx
[#3543](https://github.com/Giveth/giveth-dapps-v2/issues/3543#issuecomment-1902674852)
=> fix SPL token balance issue

src/components/menu/UserItems.tsx, src/components/menu/common.tsx, src/components/modals/SwitchNetwork.tsx, src/components/views/donate/CryptoDonation.tsx, src/components/views/donate/SwitchToAcceptedChain.tsx
https://github.com/Giveth/giveth-dapps-v2/issues/3399#issuecomment-1903873761
=> Update switch network of donation and menu

pages/api/donation-backup.js, pages/test2.tsx, sentry.client.config.js, src/configuration.ts, src/services/donation.ts
=> Update sentry configs

src/components/views/donate/DonateModal.tsx
=> Showing no error when Giveth wallet address doesn't exist

public/crawlable.txt
=> add onboarding to allow list

pages/verification/[slug]/index.tsx, src/components/views/project/projectDonations/ProjectDonations.index.tsx
https://discord.com/channels/679428761438912522/1198997069675896832/1202300223721046106
=> stop sending redundant and incomplete requests

lang/ca.json, lang/en.json, lang/es.json, src/components/views/create/AlloProtocol/AlloProtocolModal.tsx, src/components/views/donate/AlloProtocolFirstDonationModal.tsx, src/components/views/donate/RecurringDonationCard.tsx, src/components/views/donate/RecurringDonationModal/RecurringDonationModal.tsx, src/context/donate.context.tsx
=> Allo for donation

src/lib/constants/constants.ts
=> fix op flowrate

src/components/views/userProfile/ProfileOverviewTab.tsx
=> hide passport on public profile

src/components/views/create/categoryInput/CategoryInput.tsx, src/configuration.ts
=> Hide qf specific categories from create page

src/apollo/gql/gqlDonations.ts, src/hooks/useCreateEvmDonation.tsx
=> Add draft donation

lang/ca.json, lang/en.json, lang/es.json, src/components/views/create/AddressInterface.tsx
=> disable delete anchor contract optimism address

src/components/views/userProfile/UserProfile.view.tsx
=> fix profile incomplete issue

src/apollo/gql/gqlProjects.ts
=> Fix superfluid queries

src/components/project-card/ProjectCard.tsx, src/components/project-card/RoundNotStartedModal.tsx
=> Improve ux of not started round

pages/test2.tsx, src/components/views/homepage/HomeFromBlog.tsx, src/lib/constants/regex.ts
https://github.com/Giveth/giveth-dapps-v2/issues/3717
Reported by Ashley - looks like the rss feed no longer gives us the thumbnail image directly 
made a regex search for the img src and got the first result in the description field - which is the banner image for the post
=> add regex search for banner link in description

src/components/views/projects/qfBanner/ActiveQFProjectsBanner.tsx, src/components/views/projects/qfBanner/common.ts
This is a fixed for renaming QFBanner to activeQFBanner since we need to have another QFBanner called ArchivedQFBanner,
=> Update new round banner with new structure

src/components/views/create/CreateProject.tsx
=> fix multiple publish

src/components/views/create/AddressInterface.tsx
=> remove bg-color from anchorcontract trash

src/config/development.tsx
- Giveth/impact-graph#1368
- Giveth/impact-graph#1361
=> Add SuperFluid OP Sepolia tokens 

lang/ca.json, lang/en.json, lang/es.json, src/components/views/userProfile/projectsTab/ProjectItem.tsx, src/components/views/userProfile/projectsTab/ProjectQFStatus.tsx
=> Fix project item

src/apollo/gql/gqlQF.ts, src/components/views/projects/ActiveQFRoundStats.tsx, src/components/views/projects/ArchivedQFRoundStats.tsx, src/components/views/projects/ProjectsIndex.tsx
=> Add active qf round stats

next.config.js
=> redirect /user forever

src/components/views/create/AlloProtocol/AlloProtocolModal.tsx
=> changed nonce

src/components/views/donate/SelectTokenModal/TokenInfo.tsx, src/config/development.tsx
=> Fix supertoken icon issue

src/components/views/project/projectActionCard/AdminActions.tsx
=> add claim to adminActions

src/components/views/userProfile/projectsTab/ClaimRecurringDonationModal.tsx, src/components/views/userProfile/projectsTab/ClaimWithdrawalModal.tsx, src/hooks/useProjectClaimableDonations.ts
=> Add refetch to claim balance

src/components/views/donate/SelectTokenModal/SelectTokenModal.tsx, src/components/views/donate/SelectTokenModal/StreamInfo.tsx
=> fix icon issue

src/apollo/gql/gqlProjects.ts
=> fix name issue

src/components/views/project/projectActionCard/QFSection.tsx
=> Projects donation amount issue

src/components/views/donate/RecurringDonationCard.tsx, src/helpers/donate.ts
=> Fix wrong amount after creating allo address

src/components/views/donate/DonationInfo.tsx, src/components/views/donate/SuccessView.tsx
=> updated donation success view

src/components/views/create/AlloProtocol/AlloProtocolModal.tsx, src/components/views/donate/AlloProtocolFirstDonationModal.tsx, src/lib/helpers.ts
=> Fix anchor issue donation modal

src/components/views/donate/RecurringDonationCard.tsx, src/components/views/donate/RecurringDonationModal/RecurringDonationModal.tsx, src/helpers/donate.ts
=> Fix batch call giveth donation

src/apollo/types/types.ts, src/components/badges/RecurringDonationStatusBadge.tsx, src/components/views/userProfile/donationsTab/recurringTab/ArchiveStreamModal.tsx, src/components/views/userProfile/donationsTab/recurringTab/RecurringDonationsTable.tsx, src/components/views/userProfile/donationsTab/recurringTab/StreamActionButton.tsx, src/services/donation.ts
based on the Discord conversation.
=> Fix recurring donation action items

src/components/views/donate/RecurringDonationCard.tsx
=> Fix slider exceed on projects with no donation

src/components/views/donate/RecurringDonationCard.tsx
=> Check sign of user in recurring donation flow

src/components/views/donate/RecurringDonationCard.tsx, src/components/views/userProfile/ProfileContributes.tsx, src/components/views/userProfile/donationsTab/ProfileDonationsTab.tsx, src/lib/constants/Routes.ts
=> Add manage recurring donation link

src/config/development.tsx, src/config/production.tsx, src/types/superFluid.ts
=> add coingeckoId for superfluid tokens

src/components/views/project/projectActionCard/AdminActions.tsx, src/components/views/userProfile/projectsTab/ProjectActions.tsx
=> Claim switch network

src/components/views/userProfile/donationsTab/recurringTab/StreamActionButton.tsx
=> fix next start new donation link

lang/ca.json, lang/en.json, lang/es.json, lang/nt_ca.json, lang/nt_es.json, lang/t_ca.json, lang/t_es.json, src/components/project-card/ProjectCard.tsx, src/components/views/donate/EstimatedMatchingToast.tsx
=> Show amount raised all time on project card

src/components/views/userProfile/donationsTab/recurringTab/ArchiveStreamModal.tsx, src/components/views/userProfile/donationsTab/recurringTab/EndStreamModal.tsx
=> Fix end and archive modals title

src/apollo/gql/gqlSuperfluid.ts
=> updated queries

src/components/views/userProfile/donationsTab/recurringTab/ArchiveStreamModal.tsx
=> fix automatically close modal issue

src/components/views/userProfile/donationsTab/ProfileDonationsTab.tsx, src/components/views/userProfile/donationsTab/recurringTab/ActiveStreamsSection.tsx, src/components/views/userProfile/donationsTab/recurringTab/ModifyStreamModal/ModifyStreamModal.tsx, src/components/views/userProfile/donationsTab/recurringTab/ModifyStreamModal/UpdateStreamInnerModal.tsx, src/components/views/userProfile/donationsTab/recurringTab/ProfileDonateTab.context.tsx, src/components/views/userProfile/donationsTab/recurringTab/RecurringTab.tsx, src/context/donate.context.tsx, src/hooks/useUserStreams.ts
=> Update active streams section on modify rate

src/components/views/donate/RecurringDonationCard.tsx, src/components/views/donate/SelectTokenModal/StreamInfo.tsx, src/components/views/userProfile/donationsTab/recurringTab/ModifyStreamModal/ModifyStreamInnerModal.tsx, src/components/views/userProfile/donationsTab/recurringTab/StreamRow.tsx, src/helpers/donate.ts
=> Fix stream projects count

src/components/views/donate/RecurringDonationCard.tsx
=> disable on zero percentage

src/components/views/projects/ActiveQFRoundStats.tsx, src/components/views/projects/ArchivedQFRoundStats.tsx
=> Change copy of qf stats banner

src/components/Dropdown.tsx, src/components/views/project/projectActionCard/AdminActions.tsx, src/components/views/userProfile/donationsTab/recurringTab/StreamActionButton.tsx
=> Update recurring donation actions styles

src/components/project-card/ProjectCard.tsx, src/components/project-card/RoundNotStartedModal.tsx, src/components/views/donate/CryptoDonation.tsx, src/components/views/donate/DonateQFEligibleNetworks.tsx, src/components/views/donate/EstimatedMatchingToast.tsx, src/components/views/donate/QFModal.tsx, src/components/views/donate/SuccessView.tsx, src/components/views/project/projectActionCard/ProjectEligibleQFChains.tsx, src/components/views/project/projectActionCard/QFSection.tsx, src/components/views/project/projectDonations/NoDonation.tsx, src/components/views/userProfile/projectsTab/ProjectQFStatus.tsx, src/helpers/qf.ts, src/hooks/useAlreadyDonatedToProject.ts
=> Show hint modal on donate not started round

src/components/views/project/projectActionCard/QFSection.tsx
=> update QF for donate page

src/components/views/userProfile/donationsTab/recurringTab/ArchiveStreamModal.tsx, src/components/views/userProfile/donationsTab/recurringTab/ModifyStreamModal/ModifyStreamModal.tsx
=> fix modal closes

src/components/views/userProfile/donationsTab/recurringTab/RecurringTab.tsx
=> show ActiveStreamsSection for my account

src/components/views/userProfile/ProfileContributes.tsx
=> fix tab links

src/components/views/userProfile/donationsTab/recurringTab/ActiveProjectsSection.tsx
=> hide table filtering for public views

src/components/views/userProfile/donationsTab/recurringTab/StreamActionButton.tsx
=> hide-actions-for-archive-donations

src/apollo/gql/gqlSuperfluid.ts, src/components/views/donate/RecurringDonationModal/RecurringDonationModal.tsx, src/services/donation.ts
=> Send is batch for creating batch donation

src/components/views/donate/AlloProtocolFirstDonationModal.tsx
=> show error on invalid address

src/components/views/donate/RecurringDonationModal/RecurringDonationModal.tsx, src/components/views/userProfile/donationsTab/recurringTab/ModifyStreamModal/UpdateStreamInnerModal.tsx
=> Update saving donations in db

src/components/views/userProfile/donationsTab/recurringTab/ModifyStreamModal/UpdateStreamInnerModal.tsx
=> refetch token stream with delay

src/components/views/userProfile/donationsTab/recurringTab/ActiveStreamsSection.tsx, src/lib/constants/links.ts
=> Add explanation to streamable token balances

src/components/views/userProfile/donationsTab/recurringTab/ArchiveStreamModal.tsx, src/components/views/userProfile/donationsTab/recurringTab/EndStreamModal.tsx, src/components/views/userProfile/donationsTab/recurringTab/ModifyStreamModal/ModifyStreamModal.tsx, src/components/views/userProfile/donationsTab/recurringTab/ModifyStreamModal/UpdateStreamInnerModal.tsx, src/services/donation.ts
=> Fix modifying stream

src/components/views/donate/DonationCard.tsx, src/components/views/project/projectDonations/NoDonation.tsx, src/components/views/project/projectDonations/ProjectRecurringDonationTable.tsx, src/components/views/userProfile/donationsTab/recurringTab/StreamActionButton.tsx, src/lib/routeCreators.tsx
=> Fix no donation link for recurring tab

package.json, src/config/production.tsx
=> Fix giv buy link

src/components/modals/StakeLock/StakeGIV.tsx, src/config/production.tsx, src/types/config.ts
=> Merge buy link and giv buy link

src/components/views/create/CreateHeader.tsx
=> fix description calculation

lang/ca.json, lang/en.json, lang/es.json, src/components/views/donate/ModifySuperToken/DepositSuperToken.tsx, src/components/views/donate/ModifySuperToken/ModifySuperTokenModal.tsx, src/components/views/donate/ModifySuperToken/WithDrawSuperToken.tsx, src/components/views/userProfile/donationsTab/recurringTab/StreamRow.tsx
=> Updating stream balance after modifing

src/components/views/userProfile/donationsTab/recurringTab/StreamRow.tsx
=> show -- on zero flow rate

src/components/views/donate/RecurringDonationCard.tsx, src/components/views/donate/RecurringDonationModal/RecurringDonationModal.tsx
=> Fix hide giveth percentage row on giveth project

src/components/views/project/projectDonations/ProjectRecurringDonationTable.tsx
=> fetch ended donations too

src/components/views/donate/ModifySuperToken/StreamInfo.tsx
=> Fix deposit withdraw projects count

src/components/views/donate/ModifySuperToken/ModifySection.tsx
=> show zero on negative amount in withdraw section

src/components/views/userProfile/donationsTab/recurringTab/StreamRow.tsx
=> use totalFlowRate instead of run out

src/components/views/userProfile/donationsTab/recurringTab/ActiveProjectsSection.tsx, src/components/views/userProfile/donationsTab/recurringTab/RecurringDonationsTable.tsx
=> Show ended donations on public profile

src/components/views/donate/SelectTokenModal/StreamInfo.tsx
=> show dash on zero flow rate

src/components/views/userProfile/donationsTab/recurringTab/ActiveProjectsSection.tsx
=> show archived on public profile

src/components/views/donate/DonateIndex.tsx, src/components/views/donate/DonationCard.tsx
=> Hide incorrect estimate toast on recurring donation card

src/components/views/donate/DonateIndex.tsx, src/components/views/donate/DonateModal.tsx, src/components/views/donate/DonationInfo.tsx, src/components/views/donate/RecurringDonationModal/RecurringDonationModal.tsx, src/components/views/donate/SuccessView.tsx, src/context/donate.context.tsx
=> Remove qf section from success view

src/components/views/donate/DonateIndex.tsx
=> Show normal card on recurring donation card side

src/components/views/donate/RecurringDonationCard.tsx, src/features/user/user.slice.ts
=> Fix unauthorized problem

src/components/views/donate/DonateIndex.tsx, src/components/views/project/projectDonations/ProjectDonations.index.tsx, src/components/views/project/projectDonations/QfRoundSelector.tsx
=> show recurring tab only if isRecurringActive

src/components/views/donate/SelectTokenModal/StreamInfo.tsx, src/components/views/donate/TokenIcon/TokenIconWithGIVBack.tsx
=> Hide givback icon on supertoken

src/components/views/donate/DonatePageProjectDescription.tsx, src/components/views/donate/SuccessView.tsx
=> Hide raised amount on success view

src/components/modals/ConfirmSubmit.tsx, src/components/modals/HarvestAll.tsx
=> add margin to failed message

lang/ca.json, lang/en.json, lang/es.json, src/components/views/donate/ModifySuperToken/DepositSuperToken.tsx, src/components/views/donate/ModifySuperToken/ModifyInfoToast.tsx, src/components/views/donate/ModifySuperToken/WithDrawSuperToken.tsx
=> fix: add success Toast upon a successful withdrawal

src/components/cards/StakingCards/BaseStakingCard/StakeTogetherCard.tsx, src/lib/constants/links.ts
=> Update stake together links

src/components/views/verification/projectContact/ProjectContactIndex.tsx, src/components/views/verification/projectContact/common.types.ts
=> fix: add back project link input to contact verification

src/components/views/projects/ActiveQFRoundStats.tsx, src/components/views/projects/ArchivedQFRoundStats.tsx
=> hotfix: labels modifs

src/components/views/donate/ModifySuperToken/DepositSuperToken.tsx, src/components/views/donate/ModifySuperToken/WithDrawSuperToken.tsx, src/components/views/donate/RecurringDonationModal/RecurringDonationModal.tsx, src/components/views/userProfile/donationsTab/recurringTab/ModifyStreamModal/UpdateStreamInnerModal.tsx, src/components/views/userProfile/projectsTab/ClaimWithdrawalModal.tsx, src/helpers/network.ts
=> Fix: handle wrong network

src/components/AmountInput/AmountInput.tsx, src/components/modals/StakeLock/Lock.tsx, src/components/modals/StakeLock/Stake.tsx, src/components/modals/StakeLock/StakeGIV.tsx, src/components/modals/Unstake/UnStake.tsx, src/components/views/donate/ModifySuperToken/DepositSuperToken.tsx, src/components/views/donate/ModifySuperToken/ModifySection.tsx, src/components/views/donate/ModifySuperToken/WithDrawSuperToken.tsx, src/components/views/donate/RecurringDonationCard.tsx
=> Add max to recurring donation

src/components/views/donate/ManageRecurringDonation.tsx, src/components/views/donate/SuccessView.tsx, src/context/donate.context.tsx
=> Update success page for recurring donations

src/apollo/gql/gqlUser.ts, src/components/views/onboarding/InfoStep.tsx
https://github.com/Giveth/impact-graph/issues/1511
=> Trigger ortto activity when user saves their profile info for the first time

pages/qf-archive/[slug].tsx, src/components/views/projects/MiddleBanners/QFMiddleBanner.tsx, src/components/views/projects/ProjectsIndex.tsx, src/components/views/projects/qfBanner/ArchivedQFProjectsBanner.tsx, src/hooks/usePassport.ts
Related to #3250 & #3675
- remove 'Desktop'
- Add passport banner (with ended status)
- Apply dynamic Middle banner to Archived QF Rounds
=> fix: Archived QF rounds issues

src/components/views/userProfile/donationsTab/oneTimeTab/OneTimeDonationsTable.tsx
Resolve #4138
@RamRamez, cc @jainkrati, when you have time please can you review this pull request.
Only problem that I have now is how to check _private view_ is it working like it should, to check table view with _status_ column included. Is there any option to log on development side with some other test user and check admin/private options?
Thx
=> Network column inside user donation

src/apollo/types/types.ts, src/components/views/create/CreateProject.tsx, src/components/views/create/SocialMediaBox/SocialMedias.tsx, src/components/views/create/types.tsx, src/components/views/project/ProjectSocialItem.tsx
=> [Create/Edit Project]: add telegram input to social links

src/components/views/donate/SuccessView.tsx, src/lib/constants/shareContent.ts
Resolve #4085 
@MohammadPCh please review when you get time
cc @jainkrati
=> Resolve custom twitter recurring message

src/components/views/donate/RecurringDonationModal/RecurringDonationModal.tsx, src/components/views/donate/SelectTokenModal/StreamInfo.tsx, src/components/views/donate/SelectTokenModal/TokenInfo.tsx
=> Show givback info on recurring donations

src/config/development.tsx, src/config/production.tsx
https://github.com/Giveth/impact-graph/issues/934
=> Add giveth tag to subgraph queries

pages/donate/[slug].tsx, pages/project/[projectIdSlug]/index.tsx, pages/success/[slug].tsx, pages/verification/[slug]/index.tsx, src/apollo/gql/gqlProjects.ts, src/components/SocialBox.tsx, src/components/project-card/ProjectCardAlt.tsx, src/context/donate.context.tsx, src/context/project.context.tsx
https://github.com/Giveth/impact-graph/issues/1531
=> Optimize project by slug query

src/components/views/verification/menu/MobileMenu.tsx
=> Problem showing menu in Verification view in mobile

src/features/price/price.services.ts
I used native fetch function instead of our custom gqlRequest function, since it's not supporting params for graphql request
https://github.com/Giveth/impact-graph/issues/934
=> fix giveth tag for subgraph queries

package.json, src/components/ImageUploader.tsx, src/components/views/create/CreateProject.tsx
=> Hot fix create issues

pages/user/[address].tsx, src/components/views/userProfile/donationsTab/ProfileDonationsTab.tsx, src/components/views/userProfile/projectsTab/ProfileProjectsTab.tsx, src/helpers/user.ts
=> Handle users with no name

src/components/views/userProfile/projectsTab/ProjectItem.tsx
=> fix project action size

src/components/views/donate/DonateIndex.tsx
=> PassPort banner is hidden under header

package.json, src/components/views/donate/DonateIndex.tsx, src/components/views/donate/NiceBanner.tsx
=> Hotfix - nice banner and donate card is hidden under header

src/components/modals/ManageProjectAddresses/AddNewAddress.tsx, src/components/modals/ManageProjectAddresses/ManageProjectAddressesModal.tsx, src/components/modals/deactivateProject/DeactivateProjectIndex.tsx, src/components/views/project/projectActionCard/AdminActions.tsx, src/components/views/userProfile/projectsTab/ProfileProjectsTab.tsx, src/components/views/userProfile/projectsTab/ProjectActions.tsx, src/components/views/userProfile/projectsTab/ProjectItem.tsx
=> Fix project actions

lang/en.json
=> fix typo giv-earth round

src/components/views/donate/EstimatedMatchingToast.tsx
=> Fix: format min USD value for estimated matching to be counted

src/components/views/donate/OnTime/SelectTokenModal/TokenInfo.tsx, src/components/views/project/projectActionCard/QFSection.tsx
=> Show selected token

src/apollo/gql/gqlDonations.ts, src/components/views/donate/DonateModal.tsx, src/components/views/donate/helpers.tsx, src/hooks/useCreateEvmDonation.tsx, src/hooks/useCreateSolanaDonation.tsx, src/services/donation.ts
…-donation-box
Add useDonationBox and relevantDonationTxHash fields to donation attributes and send it to backend
=> release add new fields to donation

src/components/AmountInput/AmountInput.tsx, src/components/views/donate/OnTime/OneTimeDonationCard.tsx, src/context/donate.context.tsx
=> Hotfix fix donate token and amount

src/hooks/usePassport.ts
=> Fix: show error banner after checking round

src/components/AmountInput/AmountInput.tsx, src/components/modals/ModalHeader.tsx, src/components/views/donate/OnTime/OneTimeDonationCard.tsx
=> Fix remove balance on not selected token

package.json, src/components/modals/StakeLock/StakeGIV.tsx
=> fix: remove option for permit stake on OPT network

src/components/views/homepage/whyGiveth/index.tsx
@mohammadranjbarz noticed there may be a problem in staging with the recentDonations query, some of those are coming with empty users - this PR fixes this on the frontend but we should take care of it on the backend
CC @CarlosQ96 @RamRamez
=> HOTFIX: on build breaking develop

src/components/views/donate/DonationCard.tsx
modify condition from https://github.com/Giveth/giveth-dapps-v2/pull/4623/files to check if projects do not have endaoment label in order to show recurring donation view in donation flow
=> hotifx: prevent projects with Endaoment label from showing recurring donation view

src/components/GIVeconomyPages/GIVfarm.sc.tsx
related to https://github.com/Giveth/giveth-dapps-v2/issues/4673#issuecomment-2327446052
=> Modify some changes in the lock modal for not started farms

src/components/views/donate/DonationCard.tsx
=> HOTFIX: Comment-out-recurring-donation-default

package.json, src/hooks/useStakingPool.ts
=> Givfarm aprs on other chains should show up when connected to any chain

src/components/NetworkSelector.tsx
related to  https://github.com/Giveth/giveth-dapps-v2/issues/4783#event-14403871038
=> Hotfix - Add mainnet and sepolia to network selector

src/components/views/givfarm/GIVfarmBottom.tsx
- https://github.com/Giveth/giveth-dapps-v2/issues/4851
=> removed stake together

next-env.d.ts, src/config/production.tsx
=> Disable USDC on recurring donation

src/components/GIVeconomyPages/GIVstream.tsx, src/components/givfarm/RegenStreamSection.tsx, src/components/modals/VerificationModal.tsx, src/components/views/about/AboutHistory.tsx, src/components/views/claim/cards/Connect.tsx, src/components/views/donate/DonatePageProjectDescription.tsx, src/components/views/homepage/InformationBlock.tsx, src/components/views/homepage/TorusBanner.tsx, src/components/views/homepage/aboutGiveconomy/index.tsx, src/components/views/landings/onboarding/main/WhatIsGIV.tsx, src/components/views/nft/overview/EligibilityModal.tsx, src/components/views/nft/overview/WhatElse.tsx, src/components/views/project/ProjectDevouchBox.tsx, src/components/views/project/projectActionCard/DonationSection.tsx, src/content/FAQ.tsx, src/lib/constants/links.ts
fix broken links on production as result of docs migration to notion
=> HOTFIX: update docs links + update hardcoded docs links

pages/sitemap.xml.ts
- https://github.com/Giveth/giveth-dapps-v2/issues/915
=> Improving SEO Sitemap

src/components/SocialBox.tsx
- https://github.com/Giveth/giveth-dapps-v2/issues/5061
=> HOTFIX: Update social text for new QF Round

src/components/SocialBox.tsx
- https://github.com/Giveth/giveth-dapps-v2/issues/5073
=> HOTFIX: Remove last QF round share text

package.json, src/hooks/useCreateEvmDonation.tsx, src/lib/helpers.ts, src/providers/generalWalletProvider.tsx, yarn.lock
- https://github.com/Giveth/giveth-dapps-v2/issues/5105
=> hotfix: add divvi referral for Celo to production

src/components/views/causes/create/CauseReviewStep.tsx
- https://github.com/Giveth/giveth-dapps-v2/issues/5215#issuecomment-3155060769
=> Fixing text in two lines

src/components/views/causes/create/CauseReviewStep.tsx, src/components/views/causes/create/CauseSelectProjectsStep.tsx, src/components/views/causes/create/CreateCause.tsx, src/components/views/causes/edit/EditCause.tsx, src/components/views/causes/edit/EditCauseSelectProjectsStep.tsx
- https://github.com/Giveth/giveth-dapps-v2/issues/5302
=> HOTFIX: creating cause without category
